// Phase 4B.3C — Careers, Mentoring, Workload, and Team Growth
const CAREER_VERSION=1;
const JUNIOR_NPCS=[
  {id:'jordan',name:'Jordan Kim',role:'Training Engineer',level:'Engineer II',avatar:'JK',color:'cyan',specialty:'Training loops',bio:'Strong Python and PyTorch fundamentals; developing distributed-systems judgment and incident experience.',skills:{distributed:3,nccl:2,training:6,data:3,evals:3,inference:3,post:2,safety:2},bias:'systems',trait:'Asks careful questions and learns quickly from concrete failures.'},
  {id:'sofia',name:'Sofia Alvarez',role:'Evals Engineer',level:'Engineer I',avatar:'SA',color:'teal',specialty:'Evaluation harnesses',bio:'Strong data analysis instincts; growing contamination-detection and production incident experience.',skills:{distributed:2,nccl:1,training:3,data:5,evals:6,inference:2,post:4,safety:4},bias:'evals',trait:'Wants to understand why a metric is trustworthy before optimizing it.'}
];
const CAREER_LADDER=['Engineer I','Engineer II','Senior','Staff','Principal','Distinguished'];
function careerDefaults(e){
  e.experience ||= {distributed:0,training:0,data:0,evals:0,inference:0,post:0,safety:0,research:0,incidentLeadership:0,mentoring:0};
  e.leadershipSkills ||= {technicalJudgment:4,incidentLeadership:3,communication:5,mentoring:3,systemsThinking:4};
  e.relationships ||= {trust:e.trust??55,respect:e.respect??55,alignment:e.alignment??55,autonomy:55,psychologicalSafety:62};
  e.career ||= {level:e.level||'Senior',ambitions:[],promotionHistory:[],stretchAssignments:[],externalOffers:[],lastEventDay:0};
  e.career.level ||= e.level||'Senior';e.level=e.career.level;
  e.workloadState ||= {current:e.workload??25,sources:[],status:'healthy'};
  e.mentoring ||= {mentorIds:[],menteeIds:[],sessions:0};
  e.careerCredits ||= {incidents:[],actions:[],knowledge:[],experiments:[]};
}
function ensureCareerState(){
  if(typeof ensureNpcTeam==='function')ensureNpcTeam();
  state.careers ||= {version:CAREER_VERSION,selectedId:state.npcTeam?.selectedId||'maya',mentoringEvents:[],careerEvents:[],nextEventId:1};
  JUNIOR_NPCS.forEach(t=>{if(!state.npcEmployees.some(e=>e.id===t.id))state.npcEmployees.push({...t,trust:55,respect:55,alignment:55,workload:18,memories:[],ideasGenerated:0,incidentsHelped:0,discoveries:[]})});
  state.npcEmployees.forEach(careerDefaults);syncCareerProgress();
}
function domainFromIncidentType(type){const inc={id:type};return typeof incidentDomain==='function'?incidentDomain(inc):'training'}
function gainXp(e,domain,amount,reason){careerDefaults(e);e.experience[domain]=(e.experience[domain]||0)+amount;const skillKey=domain==='research'?'systemsThinking':domain==='incidentLeadership'?'incidentLeadership':null;if(skillKey)e.leadershipSkills[skillKey]=Math.min(10,e.leadershipSkills[skillKey]+amount/500);if(reason&&typeof npcRemember==='function')npcRemember(e,`${reason} (+${amount} ${domain} experience).`,'career')}
function syncCareerProgress(){
  if(!state.organization)return;
  for(const r of state.organization.incidents||[]){if(r.status!=='resolved')continue;for(const p of Object.values(r.participants||{})){const e=state.npcEmployees.find(x=>x.id===p.employeeId);if(!e||e.careerCredits.incidents.includes(r.id))continue;const d=domainFromIncidentType(r.incidentType),base=20+(p.consultations||0)*5+(p.evidenceSeen?.length||0)*6;gainXp(e,d,base,`Worked ${r.title}`);if(p.role==='Lead'||p.role==='Incident Commander')gainXp(e,'incidentLeadership',18,`Led ${r.title}`);e.careerCredits.incidents.push(r.id)}}
  for(const a of state.organization.actionItems||[]){if(a.status!=='complete')continue;const e=state.npcEmployees.find(x=>x.id===a.ownerId);if(!e||e.careerCredits.actions.includes(a.id))continue;gainXp(e,'incidentLeadership',8,`Completed corrective action: ${a.title}`);e.careerCredits.actions.push(a.id)}
  for(const k of state.organization.knowledge||[]){for(const id of k.contributors||[]){const e=state.npcEmployees.find(x=>x.id===id);if(!e||e.careerCredits.knowledge.includes(k.id))continue;gainXp(e,k.domain||'research',12,`Contributed to lab knowledge: ${k.title}`);e.careerCredits.knowledge.push(k.id)}}
  state.npcEmployees.forEach(updateWorkloadState);
}
function updateWorkloadState(e){careerDefaults(e);const base=e.workload??e.workloadState.current??20;const activeActions=(state.organization?.actionItems||[]).filter(a=>a.ownerId===e.id&&a.status==='open').length*9;const mentoring=e.mentoring.menteeIds.length*5;const current=Math.max(0,Math.min(100,Math.round(base*.6+activeActions+mentoring)));e.workloadState.current=current;e.workload=current;e.workloadState.status=current<40?'healthy':current<70?'busy':current<85?'overloaded':'critical';return current}
function mentoringCandidates(mentor){return state.npcEmployees.filter(e=>e.id!==mentor.id&&CAREER_LADDER.indexOf(e.career.level)<=1)}
function startMentoring(mentorId,menteeId){ensureCareerState();const mentor=npcById(mentorId),mentee=npcById(menteeId);if(!mentor||!mentee)return;if(!mentor.mentoring.menteeIds.includes(menteeId))mentor.mentoring.menteeIds.push(menteeId);if(!mentee.mentoring.mentorIds.includes(mentorId))mentee.mentoring.mentorIds.push(mentorId);mentor.relationships.autonomy=Math.min(100,mentor.relationships.autonomy+2);mentor.relationships.trust=Math.min(100,mentor.relationships.trust+1);mentee.relationships.psychologicalSafety=Math.min(100,mentee.relationships.psychologicalSafety+4);if(typeof npcRemember==='function'){npcRemember(mentor,`Started mentoring ${mentee.name}.`,'mentoring');npcRemember(mentee,`${mentor.name} became my mentor.`,'mentoring')}save();render()}
function runMentoringSession(mentorId,menteeId){ensureCareerState();const mentor=npcById(mentorId),mentee=npcById(menteeId);if(!mentor||!mentee)return;const domain=mentor.bias==='systems'?'distributed':mentor.bias==='infra'?'distributed':mentor.bias==='research'?'training':mentor.bias;const xp=18+Math.round((mentor.skills[domain]||5)*1.5);gainXp(mentee,domain,xp,`Mentored by ${mentor.name}`);gainXp(mentor,'mentoring',12,`Mentored ${mentee.name}`);mentor.leadershipSkills.mentoring=Math.min(10,mentor.leadershipSkills.mentoring+.15);mentor.mentoring.sessions++;mentee.mentoring.sessions++;mentor.workload=Math.min(100,mentor.workload+4);state.careers.mentoringEvents.unshift({id:`MENT-${state.careers.nextEventId++}`,day:state.day,mentorId,menteeId,domain,xp});save();render()}
function promotionEvidence(e){careerDefaults(e);const level=e.career.level;const idx=CAREER_LADDER.indexOf(level);const next=idx>=0&&idx<CAREER_LADDER.length-1?CAREER_LADDER[idx+1]:null;const total=Object.values(e.experience).reduce((a,b)=>a+b,0);const domains=Object.entries(e.experience).filter(([k,v])=>!['mentoring','incidentLeadership'].includes(k)&&v>=40).length;const led=e.experience.incidentLeadership>=35;const mentoring=e.experience.mentoring>=20||e.mentoring.sessions>=2;const knowledge=e.careerCredits.knowledge.length>=1;const requirements=idx<=1?[['Relevant experience',total>=120],['Incident contribution',e.careerCredits.incidents.length>=2],['Strong performance',e.relationships.respect>=60]]:idx===2?[['Technical depth',total>=220],['Cross-domain exposure',domains>=2],['Incident leadership',led],['Organizational contribution',knowledge]]:[['Technical depth',total>=360],['Cross-domain exposure',domains>=3],['Incident leadership',e.experience.incidentLeadership>=70],['Mentoring',mentoring],['Organizational contribution',e.careerCredits.knowledge.length>=2]];return {next,requirements,eligible:!!next&&requirements.every(x=>x[1])}}
function promoteEmployee(id){const e=npcById(id);if(!e)return;const p=promotionEvidence(e);if(!p.eligible)return;const old=e.career.level;e.career.level=p.next;e.level=p.next;e.career.promotionHistory.unshift({day:state.day,from:old,to:p.next});e.relationships.respect=Math.min(100,e.relationships.respect+5);e.relationships.autonomy=Math.min(100,e.relationships.autonomy+5);if(typeof npcRemember==='function')npcRemember(e,`Promoted from ${old} to ${p.next}.`,'promotion');log(`⬆ ${e.name} promoted to ${p.next}.`);save();render()}
function assignStretch(id){const e=npcById(id);if(!e)return;const assignment={day:state.day,title:e.bias==='systems'?'Lead next model scaling review':e.bias==='evals'?'Own next eval release gate':'Own a cross-functional technical review',status:'active'};e.career.stretchAssignments.unshift(assignment);e.relationships.autonomy=Math.min(100,e.relationships.autonomy+4);e.workload=Math.min(100,e.workload+8);npcRemember(e,`Received stretch assignment: ${assignment.title}.`,'career');save();render()}
function maybeCareerEvent(e){careerDefaults(e);if(state.day-e.career.lastEventDay<7)return null;const w=updateWorkloadState(e);let event=null;if(w>=85)event={type:'workload',title:`${e.name} is overloaded`,text:`${e.name}'s workload is ${w}%. Redistributing ownership would reduce execution risk.`};else if(e.relationships.autonomy<45)event={type:'autonomy',title:`${e.name} wants more ownership`,text:`${e.name} wants clearer technical ownership instead of being used only as a consultant.`};else{const p=promotionEvidence(e);if(p.eligible)event={type:'promotion',title:`${e.name} is promotion-ready`,text:`The evidence now supports a promotion from ${e.career.level} to ${p.next}.`}}if(event){event.id=`CAREER-${state.careers.nextEventId++}`;event.employeeId=e.id;event.day=state.day;e.career.lastEventDay=state.day;state.careers.careerEvents.unshift(event)}return event}
function resolveCareerEvent(id,choice){const ev=state.careers.careerEvents.find(x=>x.id===id);if(!ev||ev.resolved)return;const e=npcById(ev.employeeId);if(choice==='promote')promoteEmployee(e.id);else if(choice==='delegate'){e.workload=Math.max(0,e.workload-18);e.relationships.trust=Math.min(100,e.relationships.trust+2)}else if(choice==='ownership'){e.relationships.autonomy=Math.min(100,e.relationships.autonomy+10);e.relationships.trust=Math.min(100,e.relationships.trust+3)}else{e.relationships.psychologicalSafety=Math.max(0,e.relationships.psychologicalSafety-2)}ev.resolved=choice;save();render()}
function careerOpen(){ensureCareerState();state.view='careers';save();render()}
function careerClose(){state.view='company';save();render()}
function careerSelect(id){state.careers.selectedId=id;save();render()}
function careerExpRows(e){return Object.entries(e.experience).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([k,v])=>`<div class="career-exp"><span>${esc(k.replace(/([A-Z])/g,' $1'))}</span><i><em style="width:${Math.min(100,v/4)}%"></em></i><b>${Math.round(v)}</b></div>`).join('')}
function renderCareerProfile(e){const p=promotionEvidence(e),mentees=mentoringCandidates(e);return `<main class="career-profile"><section class="career-card career-hero"><div class="npc-avatar giant ${e.color}">${esc(e.avatar)}</div><div><div class="eyebrow">${esc(e.career.level)} · ${esc(e.specialty)}</div><h2>${esc(e.name)}</h2><p>${esc(e.bio)}</p><div class="career-status ${e.workloadState.status}">${e.workloadState.current}% workload · ${esc(e.workloadState.status)}</div></div></section><div class="career-grid"><section class="career-card"><div class="eyebrow">DOMAIN EXPERIENCE</div>${careerExpRows(e)}</section><section class="career-card"><div class="eyebrow">LEADERSHIP</div>${Object.entries(e.leadershipSkills).map(([k,v])=>`<div class="career-lead"><span>${esc(k.replace(/([A-Z])/g,' $1'))}</span><b>${v.toFixed(1)}</b></div>`).join('')}</section><section class="career-card"><div class="eyebrow">PROFESSIONAL RELATIONSHIP</div><div class="career-rel"><div><span>Trust</span><b>${Math.round(e.relationships.trust)}</b></div><div><span>Respect</span><b>${Math.round(e.relationships.respect)}</b></div><div><span>Autonomy</span><b>${Math.round(e.relationships.autonomy)}</b></div><div><span>Psychological safety</span><b>${Math.round(e.relationships.psychologicalSafety)}</b></div></div></section><section class="career-card"><div class="eyebrow">PROMOTION REVIEW</div><h3>${p.next?`${e.career.level} → ${p.next}`:'Top of current ladder'}</h3>${p.requirements.map(([x,ok])=>`<div class="career-req ${ok?'met':''}">${ok?'✓':'○'} ${esc(x)}</div>`).join('')}<div class="career-actions">${p.eligible?`<button onclick="promoteEmployee('${e.id}')">Promote</button>`:''}${p.next&&!p.eligible?`<button onclick="assignStretch('${e.id}')">Give stretch assignment</button>`:''}</div></section><section class="career-card wide"><div class="eyebrow">MENTORING</div><h3>Develop the next layer of the team</h3><div class="mentoring-grid">${mentees.length?mentees.map(m=>{const active=e.mentoring.menteeIds.includes(m.id);return `<div class="mentee"><div><b>${esc(m.name)}</b><span>${esc(m.career.level)} · ${esc(m.specialty)}</span></div>${active?`<button onclick="runMentoringSession('${e.id}','${m.id}')">Run mentoring session</button>`:`<button onclick="startMentoring('${e.id}','${m.id}')">Start mentoring</button>`}</div>`}).join(''):'<p>No junior mentoring candidates for this employee.</p>'}</div></section></div></main>`}
function renderCareers(){ensureCareerState();state.npcEmployees.forEach(maybeCareerEvent);const e=npcById(state.careers.selectedId)||state.npcEmployees[0];const unresolved=state.careers.careerEvents.filter(x=>!x.resolved).slice(0,3);return `<div class="career-shell"><header class="career-head"><div><div class="eyebrow">PHASE 4B.3C · CAREERS + MENTORING</div><h1>The team has careers now.</h1><p>Employees accumulate domain experience, mentor juniors, earn promotions, manage workload, and react to how leadership treats autonomy and psychological safety.</p></div><button onclick="careerClose()">Return to company</button></header>${unresolved.length?`<section class="career-events">${unresolved.map(ev=>`<article><div><b>${esc(ev.title)}</b><p>${esc(ev.text)}</p></div><div>${ev.type==='promotion'?`<button onclick="resolveCareerEvent('${ev.id}','promote')">Promote</button>`:ev.type==='workload'?`<button onclick="resolveCareerEvent('${ev.id}','delegate')">Redistribute work</button>`:`<button onclick="resolveCareerEvent('${ev.id}','ownership')">Grant ownership</button>`}<button onclick="resolveCareerEvent('${ev.id}','later')">Later</button></div></article>`).join('')}</section>`:''}<div class="career-layout"><aside class="career-roster">${state.npcEmployees.map(x=>`<button class="${x.id===e.id?'active':''}" onclick="careerSelect('${x.id}')"><span class="npc-avatar ${x.color}">${esc(x.avatar)}</span><div><b>${esc(x.name)}</b><small>${esc(x.career.level)}</small></div><em class="${x.workloadState.status}">${x.workloadState.current}%</em></button>`).join('')}</aside>${renderCareerProfile(e)}</div></div>`}
const careerRender=render;
render=function(){ensureCareerState();if(state.view==='careers'){document.getElementById('app').innerHTML=renderCareers();return}careerRender();if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const b=document.createElement('button');b.className='career-launch';b.onclick=careerOpen;b.innerHTML=`<span>CAREERS</span><b>${state.npcEmployees.length} employees · ${state.npcEmployees.filter(e=>promotionEvidence(e).eligible).length} promotion-ready</b><small>Experience · mentoring · workload · promotions →</small>`;shell.insertBefore(b,shell.children[3]||null)};
render();
