// Phase 4D.19 — Dependency Graphs, Milestones, Blocked Work & Critical-Path Planning
const CRITICAL_PATH_VERSION=1;
function ensureCriticalPath(){ensurePortfolio?.();state.criticalPath ||= {version:CRITICAL_PATH_VERSION,dependencies:[],milestones:{},coordinationCost:0,blockedCount:0,criticalProjectIds:[],lastEvalDay:null};for(const p of state.portfolio.projects||[]){state.criticalPath.milestones[p.id] ||= [{id:`${p.id}-M1`,name:'Design gate',progress:25,done:p.progress>=25},{id:`${p.id}-M2`,name:'Integration gate',progress:60,done:p.progress>=60},{id:`${p.id}-M3`,name:'Release gate',progress:90,done:p.progress>=90}]};}evaluateCriticalPath()}
function addProjectDependency(projectId,dependsOnId){ensureCriticalPath();if(projectId===dependsOnId)return;const exists=state.criticalPath.dependencies.some(d=>d.projectId===projectId&&d.dependsOnId===dependsOnId);if(exists)return;state.criticalPath.dependencies.push({projectId,dependsOnId,createdDay:state.day||1});evaluateCriticalPath();save();render()}
function removeProjectDependency(projectId,dependsOnId){ensureCriticalPath();state.criticalPath.dependencies=state.criticalPath.dependencies.filter(d=>!(d.projectId===projectId&&d.dependsOnId===dependsOnId));evaluateCriticalPath();save();render()}
function dependencyBlockers(projectId){return state.criticalPath.dependencies.filter(d=>d.projectId===projectId).map(d=>state.portfolio.projects.find(p=>p.id===d.dependsOnId)).filter(p=>p&&p.status!=='delivered')}
function projectTeams(p){return new Set(projectStaff(p).map(x=>x.e.orgTeam).filter(Boolean))}
function coordinationPenalty(p){const teams=projectTeams(p).size,deps=state.criticalPath.dependencies.filter(d=>d.projectId===p.id).length;return Math.max(0,(teams-1)*.06+deps*.04)}
function projectCriticalForecast(p,memo={}){if(memo[p.id])return memo[p.id];const base=projectForecast(p),blockers=dependencyBlockers(p.id),coord=coordinationPenalty(p);let earliest=state.day||1;for(const b of blockers){const bf=projectCriticalForecast(b,memo);earliest=Math.max(earliest,bf.finishDay+1)}const duration=Math.ceil(base.eta*(1+coord));const finishDay=Math.max((state.day||1)+duration,earliest+duration);return memo[p.id]={...base,blocked:blockers.length>0,blockers,coordination:coord,finishDay,late:finishDay>p.dueDay}}
function evaluateCriticalPath(){if(!state.criticalPath||!state.portfolio)return;for(const p of state.portfolio.projects||[]){const ms=state.criticalPath.milestones[p.id]||[];ms.forEach(m=>m.done=p.progress>=m.progress||p.status==='delivered')}const active=state.portfolio.projects.filter(p=>p.status==='active'),memo={};let maxFinish=0;for(const p of active)maxFinish=Math.max(maxFinish,projectCriticalForecast(p,memo).finishDay);state.criticalPath.criticalProjectIds=active.filter(p=>projectCriticalForecast(p,memo).finishDay>=maxFinish-1).map(p=>p.id);state.criticalPath.blockedCount=active.filter(p=>dependencyBlockers(p.id).length).length;state.criticalPath.coordinationCost=Math.min(100,Math.round(active.reduce((n,p)=>n+coordinationPenalty(p)*100,0)));state.portfolio.capacityRisk=Math.min(100,(state.portfolio.capacityRisk||0)+state.criticalPath.blockedCount*5+Math.round(state.criticalPath.coordinationCost*.12))}
function completeMilestone(projectId,milestoneId){ensureCriticalPath();const p=state.portfolio.projects.find(x=>x.id===projectId),m=(state.criticalPath.milestones[projectId]||[]).find(x=>x.id===milestoneId);if(!p||!m)return;p.progress=Math.max(p.progress,m.progress);m.done=true;evaluateCriticalPath();save();render()}
if(typeof advancePortfolio==='function'){const _cpAdvance=advancePortfolio;advancePortfolio=function(){ensureCriticalPath();const blocked=new Set((state.portfolio.projects||[]).filter(p=>dependencyBlockers(p.id).length).map(p=>p.id)),before={};for(const p of state.portfolio.projects||[])before[p.id]=p.progress;_cpAdvance();for(const p of state.portfolio.projects||[])if(blocked.has(p.id)&&p.status==='active')p.progress=before[p.id];evaluateCriticalPath()}}
function criticalPathOpen(){ensureCriticalPath();state.view='criticalPath';save();render()}
function criticalPathClose(){state.view='company';save();render()}
function renderCriticalPath(){ensureCriticalPath();const active=state.portfolio.projects.filter(p=>p.status==='active'),memo={};return `<div class="cp-shell"><header class="cp-head"><div><div class="eyebrow">PHASE 4D.19 · CRITICAL PATH</div><h1>Dependencies, Milestones & Blocked Work</h1><p>Sequence projects, expose dependency risk, manage milestone gates, and see which work actually determines the portfolio finish date.</p></div><button onclick="criticalPathClose()">Return to company</button></header><section class="cp-summary"><div><span>Blocked projects</span><b>${state.criticalPath.blockedCount}</b></div><div><span>Coordination cost</span><b>${state.criticalPath.coordinationCost}%</b></div><div><span>Critical-path projects</span><b>${state.criticalPath.criticalProjectIds.length}</b></div><div><span>Dependencies</span><b>${state.criticalPath.dependencies.length}</b></div></section><section class="cp-card"><h2>Dependency graph</h2>${active.map(p=>{const f=projectCriticalForecast(p,memo),deps=state.criticalPath.dependencies.filter(d=>d.projectId===p.id);return `<div class="cp-project ${f.blocked?'blocked':''} ${state.criticalPath.criticalProjectIds.includes(p.id)?'critical':''}"><div><b>${esc(p.name)}</b><span>${p.id} · finish Day ${f.finishDay}${f.late?' · late':''}${f.blocked?' · BLOCKED':''}</span><small>${Math.round(f.coordination*100)}% coordination overhead · ${deps.length} dependencies</small></div><div>${active.filter(x=>x.id!==p.id&&!deps.some(d=>d.dependsOnId===x.id)).slice(0,4).map(x=>`<button onclick="addProjectDependency('${p.id}','${x.id}')">Depends on ${esc(x.id)}</button>`).join('')}</div>${deps.map(d=>{const x=state.portfolio.projects.find(q=>q.id===d.dependsOnId);return `<div class="cp-dep">↳ ${esc(x?.name||d.dependsOnId)} <button onclick="removeProjectDependency('${p.id}','${d.dependsOnId}')">remove</button></div>`}).join('')}<div class="cp-ms">${(state.criticalPath.milestones[p.id]||[]).map(m=>`<button class="${m.done?'done':''}" onclick="completeMilestone('${p.id}','${m.id}')">${esc(m.name)} ${m.done?'✓':m.progress+'%'}</button>`).join('')}</div></div>`}).join('')||'<p>No active projects.</p>'}</section></div>`}
const cpBaseRender=render;render=function(){ensureCriticalPath();if(state.view==='criticalPath'){document.getElementById('app').innerHTML=renderCriticalPath();return}cpBaseRender();if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const b=document.createElement('button');b.className='cp-launch';b.onclick=criticalPathOpen;b.innerHTML=`<span>CRITICAL PATH</span><b>${state.criticalPath.blockedCount} blocked · ${state.criticalPath.coordinationCost}% coordination</b><small>Dependencies · milestones · sequencing →</small>`;shell.insertBefore(b,shell.children[1]||null)};render();