// Phase 4D.33 — CEO/Executive Endgame, Succession, IPO/Acquisition & Long-Term Outcomes
const ENDGAME_VERSION=1;
function ensureExecutiveEndgame(){state.executiveEndgame ||= {version:ENDGAME_VERSION,ceoTenureDays:state.day||1,successionId:null,ipoReadiness:.45,acquisitionReadiness:.45,independenceReadiness:.55,legacyScore:50,path:null,outcome:null,history:[]};evaluateExecutiveEndgame()}
function endgameCandidates(){return (state.npcEmployees||[]).slice().sort((a,b)=>((b.promoReadiness||0)+(b.relationships?.trust||50)/100)-((a.promoReadiness||0)+(a.relationships?.trust||50)/100)).slice(0,6)}
function evaluateExecutiveEndgame(){const e=state.executiveEndgame;if(!e)return;const board=(state.governance?.boardConfidence??state.boardConfidence??55)/100,trust=(state.publicComms?.publicTrust??state.customerTrust??55)/100,safety=1-(state.aiSafetyGovernance?.residualRisk??.35),security=(state.securityGovernance?.securityPosture??.55),erm=1-(state.enterpriseRiskManagement?.enterpriseRiskScore??45)/100,program=(state.programLearning?.programMaturity??.5),platform=(state.ecosystemStrategy?.platformPower??50)/100,cash=Math.max(0,Math.min(1,(state.cash||0)/150000000));const succession=endgameCandidates()[0];const successionDepth=succession?Math.min(1,((succession.promoReadiness||.4)*.55+((succession.relationships?.trust||50)/100)*.45)):.2;e.ipoReadiness=Math.max(0,Math.min(1,board*.2+trust*.14+erm*.16+program*.12+platform*.14+cash*.12+safety*.12));e.acquisitionReadiness=Math.max(0,Math.min(1,platform*.2+security*.12+safety*.12+trust*.12+cash*.1+program*.12+board*.12+successionDepth*.1));e.independenceReadiness=Math.max(0,Math.min(1,program*.17+safety*.17+security*.15+erm*.13+cash*.13+platform*.12+successionDepth*.13));e.legacyScore=Math.round(100*Math.max(0,Math.min(1,e.ipoReadiness*.23+e.acquisitionReadiness*.18+e.independenceReadiness*.29+successionDepth*.15+trust*.15)))}
function designateSuccessor(id){ensureExecutiveEndgame();if(!npcById(id))return;state.executiveEndgame.successionId=id;const n=npcById(id);n.promoReadiness=Math.min(1,(n.promoReadiness||.4)+.06);state.executiveEndgame.history.unshift({day:state.day||1,type:'successor',id});save();render()}
function prepareEndgame(path){ensureExecutiveEndgame();const e=state.executiveEndgame;e.path=path;if(path==='ipo'){state.cash=Math.max(0,(state.cash||0)-3500000);e.ipoReadiness=Math.min(1,e.ipoReadiness+.07);state.governance&&(state.governance.boardConfidence=Math.min(100,(state.governance.boardConfidence||55)+3))}else if(path==='acquisition'){state.cash=Math.max(0,(state.cash||0)-1200000);e.acquisitionReadiness=Math.min(1,e.acquisitionReadiness+.06)}else if(path==='independent'){state.cash=Math.max(0,(state.cash||0)-1800000);e.independenceReadiness=Math.min(1,e.independenceReadiness+.06);state.customerTrust=Math.min(100,(state.customerTrust||55)+2)}else if(path==='succession'){const s=npcById(e.successionId);if(s){s.promoReadiness=Math.min(1,(s.promoReadiness||.4)+.08);s.relationships&&(s.relationships.trust=Math.min(100,(s.relationships.trust||55)+5))}}evaluateExecutiveEndgame();save();render()}
function resolveEndgame(path){ensureExecutiveEndgame();const e=state.executiveEndgame,score=path==='ipo'?e.ipoReadiness:path==='acquisition'?e.acquisitionReadiness:path==='independent'?e.independenceReadiness:Math.max(.2,(npcById(e.successionId)?.promoReadiness||0));if(score<.58)return;const quality=score>.82?'landmark':score>.68?'strong':'fragile';const names={ipo:'Public Company',acquisition:'Strategic Acquisition',independent:'Independent Frontier Lab',succession:'Leadership Succession'};e.path=path;e.outcome={day:state.day||1,path,name:names[path],quality,score,legacy:e.legacyScore};e.history.unshift({day:state.day||1,type:'outcome',path,quality});save();render()}
function executiveEndgameOpen(){ensureExecutiveEndgame();state.view='executiveEndgame';save();render()}
function executiveEndgameClose(){state.view='company';save();render()}
function renderExecutiveEndgame(){ensureExecutiveEndgame();const e=state.executiveEndgame,cands=endgameCandidates(),succ=npcById(e.successionId);if(e.outcome)return `<div class="eg-shell"><header class="eg-head"><div><div class="eyebrow">PHASE 4D.33 · ENDGAME</div><h1>${esc(e.outcome.name)}</h1><p>${esc(e.outcome.quality)} outcome · readiness ${Math.round(e.outcome.score*100)}% · legacy ${e.outcome.legacy}/100</p></div><button onclick="executiveEndgameClose()">Return</button></header><section class="eg-card"><h2>Legacy</h2><p>Your outcome reflects the company you actually built: governance, safety, security, trust, operating maturity, platform position, cash strength, and succession depth all contributed.</p></section></div>`;return `<div class="eg-shell"><header class="eg-head"><div><div class="eyebrow">PHASE 4D.33 · EXECUTIVE ENDGAME</div><h1>Succession, IPO, Acquisition & Long-Term Outcomes</h1><p>Choose what the company becomes. Endgame paths unlock only when the underlying institution is ready.</p></div><button onclick="executiveEndgameClose()">Return to company</button></header><section class="eg-summary"><div><span>Legacy score</span><b>${e.legacyScore}</b></div><div><span>IPO readiness</span><b>${Math.round(e.ipoReadiness*100)}%</b></div><div><span>Acquisition</span><b>${Math.round(e.acquisitionReadiness*100)}%</b></div><div><span>Independent</span><b>${Math.round(e.independenceReadiness*100)}%</b></div></section><section class="eg-card"><h2>Succession bench</h2><p>Designated successor: <b>${succ?esc(succ.name):'none'}</b></p><div class="eg-actions">${cands.map(n=>`<button class="${succ?.id===n.id?'on':''}" onclick="designateSuccessor('${n.id}')">${esc(n.name)} · ${Math.round((n.promoReadiness||0)*100)}%</button>`).join('')}</div></section><section class="eg-grid">${[['ipo','IPO',e.ipoReadiness],['acquisition','Acquisition',e.acquisitionReadiness],['independent','Stay Independent',e.independenceReadiness],['succession','Hand Off CEO Role',Math.max(.2,(succ?.promoReadiness||0))]].map(([id,name,score])=>`<article class="eg-card"><h2>${name}</h2><b>${Math.round(score*100)}% ready</b><p>${score>=.58?'Viable now.':'Not institutionally ready yet.'}</p><div class="eg-actions"><button onclick="prepareEndgame('${id}')">Prepare</button><button ${score<.58?'disabled':''} onclick="resolveEndgame('${id}')">Commit path</button></div></article>`).join('')}</section></div>`}
const egBaseRender=render;render=function(){ensureExecutiveEndgame();if(state.view==='executiveEndgame'){document.getElementById('app').innerHTML=renderExecutiveEndgame();return}egBaseRender();if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const b=document.createElement('button');b.className='eg-launch';b.onclick=executiveEndgameOpen;b.innerHTML=`<span>EXECUTIVE ENDGAME</span><b>Legacy ${state.executiveEndgame.legacyScore}/100 · IPO ${Math.round(state.executiveEndgame.ipoReadiness*100)}%</b><small>Succession · IPO · acquisition · independence →</small>`;shell.insertBefore(b,shell.children[1]||null)};render();

// Web startup guard: make post-start render failures visible instead of leaving the founder screen looking unresponsive.
const founderStartImpl=foundLab;
foundLab=function(){
  const c=document.getElementById('companyName')?.value?.trim()||'';
  const p=(document.getElementById('modelPrefix')?.value||'').trim().toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,10);
  if(c)state.company=c;if(p)state.prefix=p;state.started=true;save();
  try{render()}
  catch(err){
    console.error('Frontier Lab startup render failed',err);
    const app=document.getElementById('app');
    const message=esc(err?.stack||err?.message||String(err));
    if(app)app.innerHTML=`<div style="max-width:900px;margin:40px auto;padding:24px;font-family:system-ui;color:#eef2ff;background:#0b1020;border:1px solid #334155;border-radius:16px"><div class="eyebrow">STARTUP DIAGNOSTIC</div><h1>The lab was founded, but a simulation module failed to render.</h1><p>Your company state was saved. Copy the error below so the failing module can be fixed without losing the save.</p><pre style="white-space:pre-wrap;overflow:auto;padding:16px;background:#050812;border-radius:10px">${message}</pre><button onclick="state.started=false;save();location.reload()">Return to founder screen</button></div>`;
  }
};