// Phase 4D.4 — Parallel Model Families, Compatibility, EOL, Reviews, Canary/Rollback
const FAMILY_FORK_VERSION=1;
const COMPAT_SURFACES=['checkpoints','serving','tokenizer','data_pipeline','evals','posttraining'];
function ensureFamilyForkState(){
  ensureArchitectureState?.();
  state.familyForks ||= {version:FAMILY_FORK_VERSION,forks:[],reviews:[],canaries:[],eol:{},nextForkId:1,nextReviewId:1,nextCanaryId:1,history:[]};
  state.familyForks.forks ||= [];state.familyForks.reviews ||= [];state.familyForks.canaries ||= [];state.familyForks.eol ||= {};state.familyForks.history ||= [];
}
function familyById(id){ensureArchitectureState?.();return state.architecture?.portfolio?.[id]||null}
function familyRootName(id){const f=familyById(id),m=(state.models||[]).find(x=>x.id===f?.rootModelId);return m?.name||id}
function compatibilityFor(fromArch,toArch){
  const same=fromArch===toArch;const matrix={checkpoints:same?'native':'adapter',serving:same?'native':(toArch==='moe'||fromArch==='moe'?'partial':'adapter'),tokenizer:'native',data_pipeline:'native',evals:'native',posttraining:(toArch==='moe'||fromArch==='moe')?'partial':'native'};
  if((fromArch==='longctx')!==(toArch==='longctx'))matrix.tokenizer='verify';
  if((fromArch==='fp8')!==(toArch==='fp8'))matrix.checkpoints='verify';
  return matrix;
}
function compatibilityScore(matrix){const w={native:1,adapter:.72,verify:.58,partial:.38,blocked:0};return Number((Object.values(matrix).reduce((n,v)=>n+(w[v]??0),0)/Object.values(matrix).length).toFixed(2))}
function createFamilyFork(sourceFamilyId,targetArch){
  ensureFamilyForkState();const source=familyById(sourceFamilyId);if(!source||!ARCH_CHOICES[targetArch])return;
  const compat=compatibilityFor(source.architecture,targetArch),score=compatibilityScore(compat),econ=familyEconomics(sourceFamilyId),cost=Number((1.1*econ.migrationFriction*(1+(1-score))).toFixed(2));
  if((state.cashM||0)<cost){log(`Family fork requires $${cost.toFixed(2)}M.`);save();render();return}
  state.cashM-=cost;const id=`FORK-${String(state.familyForks.nextForkId++).padStart(3,'0')}`;
  const fork={id,sourceFamilyId,targetArch,status:'candidate',createdDay:state.day||1,compatibility:compat,compatibilityScore:score,costM:cost,canaryId:null,reviewId:null};state.familyForks.forks.push(fork);state.familyForks.history.push({day:state.day||1,type:'fork.created',id,sourceFamilyId,targetArch});log(`🌿 Created ${ARCH_CHOICES[targetArch].name} fork from ${familyRootName(sourceFamilyId)}.`);save();render();
}
function requestArchitectureReview(forkId){
  ensureFamilyForkState();const fork=state.familyForks.forks.find(x=>x.id===forkId);if(!fork)return;
  const source=familyById(fork.sourceFamilyId),debt=lineageDebtPortfolio(fork.sourceFamilyId),names=['maya','marcus','elena','priya'].map(id=>typeof npcById==='function'?npcById(id):null).filter(Boolean);
  const concerns=[];if(fork.compatibilityScore<.7)concerns.push('Compatibility adapters are carrying too much migration risk.');if(debt.pressure>8)concerns.push('The source family has enough unresolved debt to contaminate the fork decision.');if(fork.targetArch==='moe')concerns.push('Routing, expert balance, and serving capacity need dedicated validation.');if(fork.targetArch==='longctx')concerns.push('Long-context data and KV-cache behavior need explicit canaries.');if(!concerns.length)concerns.push('The proposal is technically coherent; proceed with a bounded canary before promotion.');
  const verdict=fork.compatibilityScore>=.75&&debt.pressure<10?'approve':fork.compatibilityScore>=.55?'conditional':'block';
  const review={id:`AR-${String(state.familyForks.nextReviewId++).padStart(3,'0')}`,forkId,day:state.day||1,verdict,reviewers:names.map(x=>x.id),concerns};state.familyForks.reviews.push(review);fork.reviewId=review.id;state.familyForks.history.push({day:state.day||1,type:'review.completed',forkId,verdict});log(`🧭 Architecture review: ${verdict.toUpperCase()} for ${fork.id}.`);save();render();
}
function startMigrationCanary(forkId){
  ensureFamilyForkState();const fork=state.familyForks.forks.find(x=>x.id===forkId);if(!fork||fork.status==='promoted')return;const review=state.familyForks.reviews.find(x=>x.id===fork.reviewId);if(review?.verdict==='block'){log('Architecture review blocks this canary.');save();render();return}
  const risk=Math.max(.08,Number((1-fork.compatibilityScore+.08).toFixed(2))),cost=Number((.35+risk*.8).toFixed(2));if((state.cashM||0)<cost){log(`Canary requires $${cost.toFixed(2)}M.`);save();render();return}
  state.cashM-=cost;state.day=(state.day||1)+1;const id=`CAN-${String(state.familyForks.nextCanaryId++).padStart(3,'0')}`;const roll=Math.random();const result=roll>risk?'pass':'fail';const canary={id,forkId,status:result,day:state.day,risk,costM:cost,metrics:result==='pass'?{lossDelta:.01,throughputDelta:.08,errorRateDelta:-.01}:{lossDelta:.11,throughputDelta:-.07,errorRateDelta:.09}};state.familyForks.canaries.push(canary);fork.canaryId=id;fork.status=result==='pass'?'canary_passed':'canary_failed';state.familyForks.history.push({day:state.day,type:'canary.'+result,forkId,id});log(`${result==='pass'?'✅':'⚠️'} Canary ${result}: ${fork.id}.`);save();render();
}
function promoteFamilyFork(forkId){
  ensureFamilyForkState();const fork=state.familyForks.forks.find(x=>x.id===forkId);if(!fork||fork.status!=='canary_passed')return;const source=familyById(fork.sourceFamilyId),newId=`${fork.sourceFamilyId}-${fork.targetArch}-${fork.id.toLowerCase()}`;if(!state.architecture.portfolio[newId])state.architecture.portfolio[newId]={familyId:newId,rootModelId:source.rootModelId,architecture:fork.targetArch,models:[],lockIn:ARCH_CHOICES[fork.targetArch].lockIn,migrationPenalty:0,history:[{day:state.day||1,type:'fork.promoted',sourceFamilyId:fork.sourceFamilyId,forkId}]};fork.status='promoted';fork.promotedFamilyId=newId;state.familyForks.history.push({day:state.day||1,type:'fork.promoted',forkId,newFamilyId:newId});log(`🚀 Promoted ${fork.id} into a parallel ${ARCH_CHOICES[fork.targetArch].name} family.`);save();render();
}
function rollbackFamilyFork(forkId){ensureFamilyForkState();const fork=state.familyForks.forks.find(x=>x.id===forkId);if(!fork||fork.status==='promoted')return;fork.status='rolled_back';fork.rolledBackDay=state.day||1;state.familyForks.history.push({day:state.day||1,type:'fork.rolled_back',forkId});log(`↩ Rolled back ${fork.id}; source family remains primary.`);save();render()}
function setFamilyLifecycle(familyId,status){ensureFamilyForkState();if(!['active','deprecated','eol'].includes(status))return;state.familyForks.eol[familyId]={status,day:state.day||1};const f=familyById(familyId);if(f)f.lifecycle=status;state.familyForks.history.push({day:state.day||1,type:'family.lifecycle',familyId,status});if(status==='eol'){(state.techDebt?.items||[]).filter(x=>x.status==='open'&&f?.models?.includes(x.modelId)).forEach(x=>{x.status='accepted';x.acceptedDay=state.day||1;x.acceptanceReason='family_eol'})}log(`${status==='eol'?'🪦':status==='deprecated'?'📉':'♻️'} ${familyRootName(familyId)} lifecycle → ${status.toUpperCase()}.`);save();render()}
function familyForkOpen(){ensureFamilyForkState();state.view='familyForks';save();render()}
function familyForkClose(){state.view='company';save();render()}
function renderCompat(matrix){return `<div class="compat-grid">${COMPAT_SURFACES.map(k=>`<div><span>${esc(k.replaceAll('_',' '))}</span><b class="compat-${matrix[k]}">${esc(matrix[k])}</b></div>`).join('')}</div>`}
function renderForkCard(fork){const review=state.familyForks.reviews.find(x=>x.id===fork.reviewId),canary=state.familyForks.canaries.find(x=>x.id===fork.canaryId);return `<article class="fork-card"><header><div><span>${esc(fork.id)} · ${esc(familyRootName(fork.sourceFamilyId))}</span><h3>${esc(ARCH_CHOICES[fork.targetArch]?.name||fork.targetArch)}</h3></div><b>${Math.round(fork.compatibilityScore*100)}% compatible</b></header>${renderCompat(fork.compatibility)}${review?`<div class="review-box"><b>Architecture review: ${esc(review.verdict)}</b>${review.concerns.map(x=>`<p>• ${esc(x)}</p>`).join('')}</div>`:''}${canary?`<div class="canary-box ${canary.status}"><b>Canary ${esc(canary.status)}</b><span>Risk ${Math.round(canary.risk*100)}% · throughput ${canary.metrics.throughputDelta>=0?'+':''}${Math.round(canary.metrics.throughputDelta*100)}%</span></div>`:''}<footer>${!fork.reviewId?`<button onclick="requestArchitectureReview('${fork.id}')">Request NPC review</button>`:''}${fork.reviewId&&!fork.canaryId?`<button onclick="startMigrationCanary('${fork.id}')">Run canary</button>`:''}${fork.status==='canary_passed'?`<button onclick="promoteFamilyFork('${fork.id}')">Promote fork</button>`:''}${!['promoted','rolled_back'].includes(fork.status)?`<button onclick="rollbackFamilyFork('${fork.id}')">Rollback</button>`:''}<span>${esc(fork.status)}</span></footer></article>`}
function renderFamilyForks(){ensureFamilyForkState();const families=Object.values(state.architecture?.portfolio||{});return `<div class="fork-shell"><header class="fork-head"><div><div class="eyebrow">PHASE 4D.4 · PORTFOLIO GOVERNANCE</div><h1>Model Family Forks & Lifecycle</h1><p>Run architectures in parallel, validate compatibility, canary migrations, and retire families without pretending every lineage can evolve forever.</p></div><button onclick="familyForkClose()">Return to company</button></header><section class="family-lifecycle">${families.map(f=>{const life=state.familyForks.eol[f.familyId]?.status||f.lifecycle||'active';return `<article><div><span>${esc(familyRootName(f.familyId))}</span><b>${esc(ARCH_CHOICES[f.architecture]?.name||f.architecture)}</b><small>${f.models.length} generations · ${Math.round((f.lockIn||0)*100)}% lock-in</small></div><div class="life-actions"><button onclick="setFamilyLifecycle('${f.familyId}','active')">Active</button><button onclick="setFamilyLifecycle('${f.familyId}','deprecated')">Deprecate</button><button onclick="setFamilyLifecycle('${f.familyId}','eol')">EOL</button></div><em>${esc(life)}</em><div class="fork-actions">${Object.keys(ARCH_CHOICES).filter(k=>k!==f.architecture).map(k=>`<button onclick="createFamilyFork('${f.familyId}','${k}')">Fork → ${esc(ARCH_CHOICES[k].name)}</button>`).join('')}</div></article>`}).join('')||'<p>No model families yet.</p>'}</section><main class="fork-grid">${state.familyForks.forks.slice().reverse().map(renderForkCard).join('')||'<section class="fork-empty"><h2>No parallel forks yet</h2><p>Fork an active family to compare another architecture without destroying the source lineage.</p></section>'}</main></div>`}
const forkBaseRender=render;
render=function(){ensureFamilyForkState();if(state.view==='familyForks'){document.getElementById('app').innerHTML=renderFamilyForks();return}forkBaseRender();if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const b=document.createElement('button');b.className='fork-launch';b.onclick=familyForkOpen;b.innerHTML=`<span>MODEL FAMILIES</span><b>${state.familyForks.forks.filter(x=>x.status!=='rolled_back').length} parallel fork${state.familyForks.forks.filter(x=>x.status!=='rolled_back').length===1?'':'s'}</b><small>Compatibility · canaries · deprecation · EOL →</small>`;shell.insertBefore(b,shell.children[1]||null)};
render();
