// P5.1.4 — FrontierOS Navigation, Notifications & Session Layer
(function(){
  'use strict';
  const SCHEMA=1,SESSION_KEY='frontieros.session.v1',MAX_HISTORY=80,MAX_RECENTS=10,MAX_NOTIFICATIONS=80;
  const runtime={history:[],index:-1,recents:[],notifications:[],centerOpen:false,suppressRecord:0,restored:false};
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const now=()=>new Date().toISOString();
  const makeId=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
  const detectSurface=()=>document.documentElement.dataset.frontierOsSurface||
    (window.frontierMobileShellSnapshot?.().active?'phone':window.frontierDesktopShellSnapshot?.().active?'desktop':'legacy');
  function readSaved(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch(e){return null}}
  function app(id){return window.frontierApp?.(id)||null}
  function routeFor(appId,detail=null){const a=app(appId);return a?`${a.route}${detail?`/${String(detail).replace(/^\/+|\/+$/g,'')}`:''}`:null}
  function snapshot(includeBodies=true){return {schemaVersion:SCHEMA,capturedAt:now(),surface:detectSurface(),history:runtime.history.map(x=>({...x})),index:runtime.index,current:runtime.history[runtime.index]||null,canBack:runtime.index>0,canForward:runtime.index>=0&&runtime.index<runtime.history.length-1,recents:runtime.recents.map(x=>({...x})),notifications:runtime.notifications.map(n=>includeBodies?{...n}:Object.fromEntries(Object.entries(n).filter(([k])=>k!=='body'))),unread:listNotifications({unreadOnly:true}).length,notificationCenterOpen:runtime.centerOpen}}
  function persist(){try{sessionStorage.setItem(SESSION_KEY,JSON.stringify(snapshot(true)))}catch(e){}}
  function touchRecent(appId,detail=null){const a=app(appId);if(!a)return;runtime.recents=runtime.recents.filter(x=>x.appId!==appId);runtime.recents.unshift({appId,detail:detail||null,label:a.label,icon:a.icon,route:routeFor(appId,detail),lastOpenedAt:now()});runtime.recents=runtime.recents.slice(0,MAX_RECENTS)}
  function pushHistory(appId,detail=null,meta={}){
    if(!appId)return null;const current=runtime.history[runtime.index];
    if(current&&current.appId===appId&&current.detail===(detail||null)){current.timestamp=now();current.surface=meta.surface||detectSurface();touchRecent(appId,detail);persist();return current}
    const entry={id:makeId('hist'),appId,route:routeFor(appId,detail),detail:detail||null,label:app(appId)?.label||appId,surface:meta.surface||detectSurface(),timestamp:now(),source:meta.source||'navigation'};
    runtime.history=runtime.history.slice(0,runtime.index+1);runtime.history.push(entry);if(runtime.history.length>MAX_HISTORY)runtime.history.shift();runtime.index=runtime.history.length-1;touchRecent(appId,detail);persist();
    window.frontierEmitEvent?.('os.navigation.changed',{direction:'push',entry,index:runtime.index,length:runtime.history.length},{source:'frontieros-session'});return entry;
  }
  async function withSuppressedRecord(fn){runtime.suppressRecord++;try{return await fn()}finally{runtime.suppressRecord=Math.max(0,runtime.suppressRecord-1)}}
  async function openOnSurface(appId,detail=null,options={}){
    const surface=options.surface||detectSurface();let result;
    result=await withSuppressedRecord(async()=>{
      if(surface==='phone'&&typeof window.frontierMobileAppOpen==='function')return await window.frontierMobileAppOpen(appId);
      if(surface==='desktop'&&typeof window.frontierDesktopAppOpen==='function')return await window.frontierDesktopAppOpen(appId);
      return await window.frontierLaunchApp?.(appId,{surface,source:'frontieros-session',payload:{detail}});
    });
    if(result?.ok&&options.record!==false)pushHistory(appId,detail,{surface,source:options.source||'navigate'});return result||{ok:false,status:'unavailable'};
  }
  async function navigate(target,options={}){
    const parsed=window.frontierParseDeepLink?.(target)||null;const appId=parsed?.appId||window.frontierResolveApp?.(target)?.id||String(target||'');const detail=options.detail??parsed?.detail??null;if(!app(appId))return {ok:false,status:'unknown',target:String(target||'')};
    const result=await openOnSurface(appId,detail,{...options,source:options.source||'frontierOsNavigate'});window.frontierEmitEvent?.('os.navigation.requested',{target:String(target||''),appId,detail,surface:options.surface||detectSurface(),result:{ok:!!result?.ok,status:result?.status}},{source:'frontieros-session'});return result;
  }
  async function travel(delta){const nextIndex=runtime.index+delta;if(nextIndex<0||nextIndex>=runtime.history.length)return {ok:false,status:'boundary'};const next=runtime.history[nextIndex];runtime.index=nextIndex;const result=await openOnSurface(next.appId,next.detail,{surface:detectSurface(),record:false,source:delta<0?'back':'forward'});persist();window.frontierEmitEvent?.('os.navigation.changed',{direction:delta<0?'back':'forward',entry:next,index:runtime.index,length:runtime.history.length,result:{ok:!!result?.ok,status:result?.status}},{source:'frontieros-session'});renderCenter();return result}
  const back=()=>travel(-1),forward=()=>travel(1);
  function home(){const surface=detectSurface();if(surface==='phone')return window.frontierMobileHomeOpen?.();if(surface==='desktop'){const s=window.frontierDesktopShellSnapshot?.();if(s?.activeApp)window.frontierDesktopWindowMinimize?.(s.activeApp);return true}return window.gameplayGoHome?.()}
  function notify(input={}){const parsed=input.deepLink?window.frontierParseDeepLink?.(input.deepLink):null;const n={id:input.id||makeId('note'),title:String(input.title||'FrontierOS'),body:String(input.body||''),appId:input.appId||parsed?.appId||null,deepLink:input.deepLink||null,severity:input.severity||'info',createdAt:input.createdAt||now(),read:false,dismissed:false,source:input.source||'runtime',sticky:!!input.sticky};runtime.notifications.unshift(n);runtime.notifications=runtime.notifications.slice(0,MAX_NOTIFICATIONS);persist();updateBadges();renderCenter();window.frontierEmitEvent?.('os.notification.created',n,{source:'frontieros-session',severity:n.severity});return {...n}}
  function listNotifications(options={}){return runtime.notifications.filter(n=>(options.includeDismissed||!n.dismissed)&&(!options.unreadOnly||(!n.read&&!n.dismissed))).map(n=>({...n}))}
  function markRead(id){const n=runtime.notifications.find(x=>x.id===id);if(!n)return false;n.read=true;persist();updateBadges();renderCenter();window.frontierEmitEvent?.('os.notification.read',{notificationId:id},{source:'frontieros-session'});return true}
  function dismiss(id){const n=runtime.notifications.find(x=>x.id===id);if(!n)return false;n.dismissed=true;n.read=true;persist();updateBadges();renderCenter();window.frontierEmitEvent?.('os.notification.dismissed',{notificationId:id},{source:'frontieros-session'});return true}
  async function openNotification(id){const n=runtime.notifications.find(x=>x.id===id);if(!n)return {ok:false,status:'unknown-notification'};markRead(id);let result={ok:true,status:'read'};if(n.deepLink||n.appId)result=await navigate(n.deepLink||n.appId,{source:'notification'});closeCenter();window.frontierEmitEvent?.('os.notification.opened',{notificationId:id,appId:n.appId,deepLink:n.deepLink,result:{ok:!!result?.ok,status:result?.status}},{source:'frontieros-session'});return result}
  function ensureCenter(){let root=document.querySelector('.frontieros-notification-center');if(root)return root;root=document.createElement('aside');root.className='frontieros-notification-center';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','FrontierOS notifications');root.innerHTML=`<header><div><strong>Notifications</strong><span data-os-note-count></span></div><button type="button" data-os-note-close aria-label="Close notifications">×</button></header><section class="frontieros-session-nav"><button type="button" data-os-back>← Back</button><button type="button" data-os-forward>Forward →</button><button type="button" data-os-home>⌂ Home</button></section><section class="frontieros-recent-apps"><h3>Recent apps</h3><div data-os-recents></div></section><section class="frontieros-notifications-list" data-os-notes></section>`;document.body.appendChild(root);root.addEventListener('click',e=>{const o=e.target.closest('[data-note-open]');if(o){openNotification(o.dataset.noteOpen);return}const d=e.target.closest('[data-note-dismiss]');if(d){dismiss(d.dataset.noteDismiss);return}const r=e.target.closest('[data-recent-app]');if(r){navigate(r.dataset.recentApp,{source:'recent'});closeCenter();return}if(e.target.closest('[data-os-note-close]'))closeCenter();if(e.target.closest('[data-os-back]'))back();if(e.target.closest('[data-os-forward]'))forward();if(e.target.closest('[data-os-home]')){home();closeCenter()}});return root}
  function renderCenter(){const root=ensureCenter(),notes=listNotifications();root.querySelector('[data-os-note-count]').textContent=`${notes.filter(n=>!n.read).length} unread`;root.querySelector('[data-os-back]').disabled=runtime.index<=0;root.querySelector('[data-os-forward]').disabled=runtime.index<0||runtime.index>=runtime.history.length-1;root.querySelector('[data-os-recents]').innerHTML=runtime.recents.length?runtime.recents.map(r=>`<button type="button" data-recent-app="${esc(r.appId)}"><span>${esc(r.icon)}</span><span>${esc(r.label)}</span></button>`).join(''):'<p>No recent apps yet.</p>';root.querySelector('[data-os-notes]').innerHTML=notes.length?notes.map(n=>`<article class="frontieros-notification ${n.read?'is-read':'is-unread'}" data-severity="${esc(n.severity)}"><button type="button" class="frontieros-notification-main" data-note-open="${esc(n.id)}"><strong>${esc(n.title)}</strong><span>${esc(n.body)}</span><small>${esc(n.appId?`Open ${app(n.appId)?.label||n.appId}`:'Notification')}</small></button><button type="button" data-note-dismiss="${esc(n.id)}" aria-label="Dismiss ${esc(n.title)}">×</button></article>`).join(''):'<div class="frontieros-notification-empty">No notifications.</div>'}
  function openCenter(){runtime.centerOpen=true;const root=ensureCenter();renderCenter();root.hidden=false;document.documentElement.classList.add('frontieros-notifications-open');root.querySelector('button')?.focus();window.frontierEmitEvent?.('os.notification-center.opened',{unread:listNotifications({unreadOnly:true}).length},{source:'frontieros-session'});return true}
  function closeCenter(){runtime.centerOpen=false;const root=ensureCenter();root.hidden=true;document.documentElement.classList.remove('frontieros-notifications-open');window.frontierEmitEvent?.('os.notification-center.closed',{}, {source:'frontieros-session'});return true}
  function updateBadges(){const count=listNotifications({unreadOnly:true}).length;document.querySelectorAll('[data-os-notification-count]').forEach(el=>{el.textContent=count?String(Math.min(count,99)):'';el.hidden=!count});document.documentElement.dataset.frontierOsUnread=String(count)}
  function attachShellControls(){const phone=document.querySelector('.frontieros-phone-dock .frontieros-dock-inner');if(phone&&!phone.querySelector('[data-os-notifications]')){const b=document.createElement('button');b.className='frontieros-dock-btn';b.dataset.osNotifications='';b.innerHTML='<strong>●</strong><span>Alerts</span><em data-os-notification-count hidden></em>';b.addEventListener('click',openCenter);phone.insertBefore(b,phone.lastElementChild)}const tray=document.querySelector('.frontieros-tray');if(tray&&!tray.querySelector('[data-os-notifications]')){const b=document.createElement('button');b.type='button';b.dataset.osNotifications='';b.setAttribute('aria-label','Open notifications');b.innerHTML='● <span data-os-notification-count hidden></span>';b.addEventListener('click',openCenter);tray.insertBefore(b,tray.firstChild)}updateBadges()}
  function loadSaved(){const saved=readSaved();if(!saved||saved.schemaVersion!==SCHEMA)return false;runtime.history=Array.isArray(saved.history)?saved.history.slice(-MAX_HISTORY):[];runtime.index=runtime.history.length?Math.max(-1,Math.min(Number(saved.index),runtime.history.length-1)):-1;runtime.recents=Array.isArray(saved.recents)?saved.recents.slice(0,MAX_RECENTS):[];runtime.notifications=Array.isArray(saved.notifications)?saved.notifications.slice(0,MAX_NOTIFICATIONS):[];runtime.restored=true;updateBadges();renderCenter();window.frontierEmitEvent?.('os.session.restored',{history:runtime.history.length,index:runtime.index,recents:runtime.recents.length,notifications:runtime.notifications.length,current:runtime.history[runtime.index]||null},{source:'frontieros-session'});return true}
  async function reopenCurrent(){const current=runtime.history[runtime.index],surface=detectSurface();if(!current||!['phone','desktop'].includes(surface))return false;const result=await openOnSurface(current.appId,current.detail,{surface,record:false,source:'session-restore'});window.frontierEmitEvent?.('os.session.current-restored',{appId:current.appId,detail:current.detail,surface,result:{ok:!!result?.ok,status:result?.status}},{source:'frontieros-session'});return !!result?.ok}
  function observe(event){const e=event.detail||event;if(!e?.type)return;const d=e.data||{};if((e.type==='os.mobile.app.opened'||e.type==='os.desktop.app.opened'||e.type==='os.desktop.window.focused')&&d.appId&&!runtime.suppressRecord)pushHistory(d.appId,null,{surface:detectSurface(),source:e.type});if(e.type==='os.mobile.shell.ready'||e.type==='os.desktop.shell.ready'){attachShellControls();if(!runtime.restored)loadSaved();queueMicrotask(reopenCurrent)}}
  window.frontierOsNavigate=navigate;window.frontierOsBack=back;window.frontierOsForward=forward;window.frontierOsHome=home;window.frontierOsRecentApps=()=>runtime.recents.map(x=>({...x}));window.frontierOsNotify=notify;window.frontierOsNotifications=listNotifications;window.frontierOsNotificationOpen=openNotification;window.frontierOsNotificationDismiss=dismiss;window.frontierOsOpenNotificationCenter=openCenter;window.frontierOsCloseNotificationCenter=closeCenter;window.frontierOsSessionSnapshot=()=>snapshot(true);window.frontierOsSessionRestore=async()=>{loadSaved();return reopenCurrent()};
  window.frontierSubscribeEvent?.('os.*',observe);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&runtime.centerOpen)closeCenter();if((e.altKey||e.metaKey)&&e.key==='ArrowLeft'){e.preventDefault();back()}if((e.altKey||e.metaKey)&&e.key==='ArrowRight'){e.preventDefault();forward()}});
  const boot=()=>{loadSaved();ensureCenter();attachShellControls();new MutationObserver(attachShellControls).observe(document.body,{childList:true,subtree:true});window.frontierEmitEvent?.('os.session.ready',{schemaVersion:SCHEMA,sessionKey:SESSION_KEY},{source:'frontieros-session'})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else queueMicrotask(boot);
})();