const SOURCES={FSDP:{title:"PyTorch FSDP",url:"https://docs.pytorch.org/docs/stable/fsdp.html"},FP8:{title:"NVIDIA Transformer Engine FP8 Primer",url:"https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html"},DPO:{title:"Direct Preference Optimization",url:"https://arxiv.org/abs/2305.18290"},FLASH:{title:"FlashAttention",url:"https://arxiv.org/abs/2205.14135"},CHINCHILLA:{title:"Chinchilla Scaling Laws",url:"https://arxiv.org/abs/2203.15556"},VLLM:{title:"PagedAttention / vLLM",url:"https://arxiv.org/abs/2309.06180"}};
const EXPLAIN={
MFU:{q:"How much theoretical accelerator math becomes useful model FLOPs.",e:"MFU compares estimated model FLOPs per second with accelerator peak throughput. Communication, pipeline bubbles, dataloading and idle time lower it.",d:"It is a model-centric teaching metric, not a replacement for kernel and collective profiling."},
TP:{q:"Split tensor operations inside a layer across GPUs.",e:"TP lowers per-GPU tensor memory but adds frequent collectives inside transformer layers.",d:"Use fast interconnects and avoid excessive TP when communication begins to dominate."},
PP:{q:"Put different layer ranges on different pipeline stages.",e:"PP lowers per-device model memory but creates fill/drain bubbles unless enough microbatches keep stages busy.",d:"Pipeline degree, microbatch count and schedule jointly determine bubble overhead."},
DP:{q:"Different replicas process different data and synchronize training state.",e:"Classic DP replicates the model; sharded variants distribute parameters, gradients and optimizer state.",d:"Global batch and communication patterns must be reasoned about together."},
FSDP:{q:"Shard model training state across data-parallel workers.",e:"PyTorch FULL_SHARD shards parameters, gradients and optimizer states and uses collectives to materialize/synchronize them.",d:"Real systems tune wrapping, prefetch, mixed precision, device mesh and distributed checkpointing.",src:"FSDP"},
BF16:{q:"16-bit float with FP32-like exponent range.",e:"BF16 is common in transformer training because of its wide exponent range and lower storage/compute cost than FP32.",d:"Training is still mixed precision; some operations and state remain higher precision."},
FP8:{q:"8-bit floating point used selectively for faster tensor-core math.",e:"Modern FP8 training uses formats such as E4M3/E5M2 plus scaling recipes. Not every operation is safe in FP8.",d:"Transformer Engine supports several scaling strategies; FP8 training is a mixed-precision system, not simply storing everything in eight bits.",src:"FP8"},
DPO:{q:"Preference optimization using chosen/rejected responses and a reference policy.",e:"DPO optimizes preferences without the explicit reward-model plus RL loop of classical RLHF.",d:"In common DPO parameterizations, larger beta applies a stronger reference-policy constraint; verify the exact implementation you are using.",src:"DPO"},
FLASH:{q:"Exact attention reorganized to reduce expensive GPU-memory traffic.",e:"FlashAttention tiles work to reduce reads/writes between HBM and on-chip memory while computing exact attention.",d:"Its central insight is IO awareness, not approximate attention.",src:"FLASH"},
KV:{q:"Cached attention keys and values from previously processed tokens.",e:"KV cache avoids recomputing earlier attention state during decoding but can dominate serving memory at long context.",d:"Paged KV systems, routing and scheduling jointly affect capacity and latency.",src:"VLLM"},
TTFT:{q:"Time from request arrival to first generated token.",e:"Queueing and prompt prefill often dominate TTFT even while decode latency stays healthy.",d:"Prompt-cost-aware routing, admission control and prefill scheduling protect interactive SLOs."},
GRAD:{q:"Magnitude of gradients before an optimizer update.",e:"Sudden spikes may indicate pathological data, instability or numerical trouble.",d:"Clipping can limit updates but should not replace root-cause diagnosis when a failure reproduces."},
CONTAM:{q:"Training data overlaps with evaluation examples or close variants.",e:"Contamination can inflate scores without genuine generalization.",d:"Use provenance, fuzzy/exact matching, temporal holdouts and decontaminated reporting."},
FLOPS:{q:"Approximate arithmetic work required by training.",e:"A common dense-transformer teaching approximation is training FLOPs ≈ 6 × parameters × tokens.",d:"Architecture, context, sparsity, recomputation and hardware inefficiency add important real-world detail.",src:"CHINCHILLA"}
};
const TECH_TREE=[{id:"flash",name:"FlashAttention",cost:2,requires:[],effect:"Training throughput +8%",term:"FLASH"},{id:"fsdp",name:"FSDP",cost:2,requires:[],effect:"Memory headroom +25%",term:"FSDP"},{id:"fp8",name:"FP8 Training",cost:3,requires:["flash"],effect:"Training throughput +14%",term:"FP8"},{id:"longctx",name:"Long Context",cost:3,requires:["flash"],effect:"Unlock 32K context research",term:"KV"},{id:"3d",name:"3D Parallelism",cost:4,requires:["fsdp"],effect:"Unlock 30B+ model tier",term:"PP"},{id:"moe",name:"Mixture of Experts",cost:6,requires:["3d","fp8"],effect:"Unlock sparse frontier tier",term:"TP"}];
const MODEL_TIERS=[{id:"350m",name:"350M Dense",paramsB:.35,minInfra:1,costM:.2,tokensB:12,rep:2},{id:"1b",name:"1.3B Dense",paramsB:1.3,minInfra:1,costM:.45,tokensB:35,rep:4},{id:"7b",name:"7B Dense",paramsB:7,minInfra:2,costM:1.8,tokensB:180,rep:9},{id:"30b",name:"30B Dense",paramsB:30,minInfra:3,costM:6.5,tokensB:650,rep:18,requires:"3d"},{id:"70b",name:"70B Dense",paramsB:70,minInfra:4,costM:14,tokensB:1500,rep:32,requires:"fp8"},{id:"moe",name:"8×22B MoE",paramsB:176,activeB:44,minInfra:5,costM:28,tokensB:3000,rep:55,requires:"moe"}];
const ROLES=["Research Scientist","Training Engineer","Data Engineer","Post-Training Engineer","Evals Engineer","Inference Engineer","Safety Engineer","Model Product Engineer","Full-Stack Frontier Engineer"];
const INCIDENTS=[
{id:"nan",role:"Training Engineer",title:"Run anomaly: gradient explosion",term:"GRAD",brief:"Loss is stable, then spikes and reaches NaN immediately after a new data shard enters the loader.",tabs:{metrics:["loss 1.923 → 1.928 → 2.741 → 6.883 → NaN","grad_norm 0.81 → 0.84 → 7.94 → 81.2 → NaN","MFU 51.6% → 50.9%"],systems:["NCCL collective latency normal","GPU clocks nominal","worker heartbeats healthy"],data:["web_en_091778 becomes active at failing step","256-example replay reproduces activation spike in blocks 57–63"]},choices:[["lr","Cut LR 10× and resume","The trigger reproduces on a specific shard; lower LR may mask symptoms without isolating it."],["data","Quarantine shard, bisect examples, add finite/activation guards, resume from verified checkpoint","Evidence localizes the trigger to the shard. Preserve and replay the bad batch, isolate the pathology, then harden validation.",true],["nccl","Replace the slowest node","Communication telemetry does not fit the failure."],["clip","Raise grad clipping from 1 to 10","That weakens a safety mechanism during an exploding-gradient event."]]},
{id:"bubble",role:"Training Engineer",title:"Scale-up: 8× GPUs, only 2.1× throughput",term:"PP",brief:"Pipeline idle time reaches 38% after PP stages increase from 2 to 8.",tabs:{metrics:["MFU 54% → 31%","PP bubble 38%","compute kernels healthy"],systems:["network packet loss none","TP collectives expected","long idle windows at pipeline fill/drain"],data:["dataloader wait <1%","global batch held constant"]},choices:[["mb","Increase microbatch count / tune schedule and reconsider PP degree","The profiler identifies pipeline bubble as dominant. More useful in-flight microbatches or less PP attacks the observed idle time.",true],["tp","Increase TP 8 → 32","More TP adds communication without fixing pipeline idle windows."],["clock","Force max clocks","Clocks are already nominal."],["wd","Lower weight decay","Optimizer regularization cannot explain pipeline idle time."]]},
{id:"contam",role:"Evals Engineer",title:"Benchmark jumped +14 points",term:"CONTAM",brief:"A private coding benchmark improves 14 points after a data refresh while controls improve only 1–3.",tabs:{metrics:["private holdout 61 → 75","control A +2","control B +1","newer temporal holdout +2.4"],systems:["evaluation harness unchanged","sampling configuration unchanged"],data:["312 prompts >0.85 MinHash similarity to training docs","196 solutions contain long matching spans from scraped tutorials"]},choices:[["ship","Announce the +14 gain","The gain conflicts with controls and there is direct overlap evidence."],["clean","Invalidate contaminated slice, trace provenance and rebuild temporal holdout","This protects measurement validity and makes the contamination auditable.",true],["temp","Raise temperature","Sampling cannot repair train/test overlap."],["variants","Add nearby variants","Variants can preserve leakage; provenance-aware clean tasks are needed."]]},
{id:"ttft",role:"Inference Engineer",title:"p99 TTFT explodes under burst load",term:"TTFT",brief:"At 3× traffic, TTFT goes 1.8s → 11.4s while inter-token latency barely changes.",tabs:{metrics:["TTFT p99 11.4s","ITL p99 35ms vs 31ms steady","GPU utilization 96%"],systems:["prefill queue 8.2s","decode queue 0.4s","KV eviction +7%"],data:["long prompts share pool with short interactive traffic","prefill consumes large contiguous compute bursts"]},choices:[["route","Use prompt-cost-aware routing, prefill caps, admission control and dedicated long-prompt capacity","The dominant problem is queued prefill; scheduling and routing protect TTFT without buying 3× hardware.",true],["spec","Only enable speculative decoding","Speculation primarily targets decode work, not the dominant prefill queue."],["kv","Disable paged KV","That can worsen memory management and does not fix scheduling."],["temp","Lower sampling temperature","Sampling temperature is unrelated to prefill queueing."]]},
{id:"dpo",role:"Post-Training Engineer",title:"DPO: helpfulness up, tool reliability down",term:"DPO",brief:"Preference win-rate improves, exact tool JSON falls 9 points, and benign refusal rises 4.1 points.",tabs:{metrics:["helpfulness +6.2 pts","tool exactness -9.0 pts","benign refusal +4.1 pts"],systems:["training stable","no loader failures"],data:["preference pairs overrepresent conversational style","tool trajectories underrepresented","higher-β pilot recovers ~5 tool points while keeping part of helpfulness gain"]},choices:[["release","Release because preference win-rate improved","Critical product slices regressed despite the aggregate gain."],["target","Rebalance data, add constraints, run beta/data ablations and gate slice regressions","This treats preference optimization as multi-objective. The higher-beta pilot is consistent with stronger reference-policy constraint.",true],["beta","Lower beta further","In common DPO implementations, lower beta permits more deviation from the reference, opposite the observed recovery direction."],["ignore","Ignore tool evals until serving","Serving cannot restore behavior lost during post-training."]]}
];
const fresh=()=>({version:3,company:"Nova Frontier",prefix:"NOVA",day:1,cashM:2.4,compute:18000,reputation:0,research:0,infra:1,employees:5,role:"Full-Stack Frontier Engineer",tech:[],models:[],activeRun:null,runHistory:[],selectedIncident:null,incidentTab:"metrics",knowledge:{},feed:["You founded a frontier-model lab. Every model, failure and breakthrough now belongs to this company."],started:false});
let state=(()=>{try{const x=JSON.parse(localStorage.getItem("frontier-lab-v3"));return x&&x.version===3?x:fresh()}catch(e){return fresh()}})();
const save=()=>localStorage.setItem("frontier-lab-v3",JSON.stringify(state));
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const fmt=(n,d=1)=>Number(n).toLocaleString(undefined,{maximumFractionDigits:d});
const money=n=>`$${fmt(n,2)}M`;
const hasTech=id=>state.tech.includes(id);
const log=m=>{state.feed.unshift(m);state.feed=state.feed.slice(0,30)};
const infraName=()=>["","Garage Lab","Colocation Suite","Private GPU Hall","Frontier Datacenter","Multi-Site Cluster","Hyperscale Campus"][state.infra]||"Frontier Campus";
const tierAvailable=t=>state.infra>=t.minInfra&&(!t.requires||hasTech(t.requires));
function foundLab(){const c=document.getElementById("companyName").value.trim(),p=document.getElementById("modelPrefix").value.trim().toUpperCase().replace(/[^A-Z0-9-]/g,"").slice(0,10);if(c)state.company=c;if(p)state.prefix=p;state.started=true;save();render()}
function switchRole(r){state.role=r;log(`Role switched to ${r}.`);save();render()}
function upgradeInfra(){const cost=[0,0,.8,2.5,7,18,40][state.infra+1];if(!cost)return;if(state.cashM<cost){log(`Infrastructure expansion requires ${money(cost)}.`);return}state.cashM-=cost;state.infra++;state.employees+=Math.round(state.infra*4);log(`🏗️ Expanded to ${infraName()}.`);save();render()}
function researchTech(id){const t=TECH_TREE.find(x=>x.id===id);if(!t||hasTech(id))return;if(!t.requires.every(x=>hasTech(x))){log("Prerequisite research is incomplete.");return}if(state.research<t.cost){log(`Need ${t.cost} research insight.`);return}state.research-=t.cost;state.tech.push(id);log(`🔬 Breakthrough: ${t.name}. ${t.effect}`);save();render()}
function trainingPhysics(t){const params=t.paramsB*1e9,tokens=t.tokensB*1e9,flops=6*params*tokens;const baseGpuHours=Math.ceil(flops/(3.3e14*3600));const boost=(hasTech("flash")?.08:0);const techBoost=(hasTech("flash")?0.08:0)+(hasTech("fp8")?0.14:0)+(hasTech("3d")?0.05:0);const gpuHours=Math.ceil(baseGpuHours/(1+techBoost));const target=t.paramsB<2?262144:t.paramsB<10?1048576:4194304;const batch=Math.max(262144,Math.round(target/8192)*8192);const steps=Math.ceil(tokens/batch);return{flops,gpuHours,batch,steps,tokens:steps*batch,techBoost}}
function nextModelName(){return `${state.prefix}-${state.models.length+1}`}
function launchTier(id){if(state.activeRun){log("Finish the active run first.");return}const t=MODEL_TIERS.find(x=>x.id===id);if(!t||!tierAvailable(t))return;const p=trainingPhysics(t);if(state.cashM<t.costM||state.compute<p.gpuHours){log(`Need ${money(t.costM)} and ${fmt(p.gpuHours,0)} simulated H100-hours.`);return}state.cashM-=t.costM;state.compute-=p.gpuHours;state.activeRun={name:nextModelName(),tier:t.id,progress:0,phase:"validation",physics:p,startedDay:state.day,loss:Math.max(2.1,5.8-Math.log10(t.paramsB+1)),incident:null};log(`🚀 ${state.activeRun.name} starts: ${fmt(p.steps,0)} steps are derived from ${fmt(p.tokens/1e9,2)}B tokens ÷ ${fmt(p.batch/1e6,3)}M tokens/update.`);save();render()}
function advanceRun(){const r=state.activeRun;if(!r)return;if(r.incident){openIncident(r.incident);return}const inc=[4,7,9,12][Math.floor(Math.random()*4)];r.progress=Math.min(100,r.progress+inc);state.day+=Math.max(1,Math.round(inc/3));r.phase=r.progress<8?"warmup":r.progress<90?"pretraining":"final evals";r.loss=Math.max(1.3,r.loss*(.965+Math.random()*.012));if(r.progress>25&&r.progress<88&&Math.random()<.24){const pool=INCIDENTS.filter(i=>state.role==="Full-Stack Frontier Engineer"||i.role===state.role||i.id==="nan");r.incident=(pool[Math.floor(Math.random()*pool.length)]||INCIDENTS[0]).id;state.selectedIncident=r.incident;log(`🔴 ${r.name}: engineering incident requires intervention.`)}if(r.progress>=100){completeRun();return}save();render()}
function completeRun(){const r=state.activeRun,t=MODEL_TIERS.find(x=>x.id===r.tier);const m={name:r.name,tier:t.name,paramsB:t.paramsB,tokensB:r.physics.tokens/1e9,steps:r.physics.steps,batch:r.physics.batch,day:state.day,score:Math.round(42+Math.log10(t.paramsB+1)*18+state.tech.length*1.5),costM:t.costM,incidents:state.runHistory.filter(x=>x.run===r.name).length};state.models.push(m);state.reputation+=t.rep;state.research+=Math.max(1,Math.round(t.rep/5));state.cashM+=Math.max(.15,t.costM*.35);state.activeRun=null;log(`🏆 ${m.name} shipped with capability index ${m.score}. It is now permanent company history.`);save();render()}
function openIncident(id){state.selectedIncident=id;state.incidentTab="metrics";save();render()}
function inspectTab(tab){state.incidentTab=tab;save();render()}
function solveIncident(id){const inc=INCIDENTS.find(i=>i.id===state.selectedIncident);if(!inc)return;const c=inc.choices.find(x=>x[0]===id),ok=!!c[3];state.knowledge[inc.term]=(state.knowledge[inc.term]||0)+(ok?2:1);log(`${ok?"✅":"⚠️"} ${inc.title}: ${c[2]}`);if(ok){state.research++;state.reputation+=2;if(state.activeRun&&state.activeRun.incident===inc.id){state.runHistory.push({run:state.activeRun.name,incident:inc.id,day:state.day});state.activeRun.incident=null}}else{state.day++;if(state.activeRun)state.activeRun.progress=Math.max(0,state.activeRun.progress-2)}state.selectedIncident=null;save();render()}
function resetGame(){if(confirm("Reset your entire company and model lineage?")){localStorage.removeItem("frontier-lab-v3");state=fresh();render()}}
function termButton(term){return `<button class="term" onclick="showExplain('${term}')">${term}<span>?</span></button>`}
function showExplain(term){const x=EXPLAIN[term];if(!x)return;const src=x.src?SOURCES[x.src]:null;document.getElementById("modalRoot").innerHTML=`<div class="modal-back" onclick="closeModal(event)"><div class="modal"><button class="x" onclick="document.getElementById('modalRoot').innerHTML=''">×</button><div class="eyebrow">TECHNICAL EXPLAINER</div><h2>${term}</h2><h3>Quick</h3><p>${x.q}</p><h3>Engineer</h3><p>${x.e}</p><h3>Deep dive</h3><p>${x.d}</p>${src?`<a class="source" href="${src.url}" target="_blank" rel="noopener">Primary source ↗ ${src.title}</a>`:""}</div></div>`}
function closeModal(e){if(e.target.classList.contains("modal-back"))document.getElementById("modalRoot").innerHTML=""}
function founderScreen(){return `<div class="founder"><div class="founder-card"><div class="logo-orbit"><i></i><i></i><i></i><b>F</b></div><div class="eyebrow">FRONTIER LAB · NEW COMPANY</div><h1>Build the model company you wish existed.</h1><p>Five people. A garage lab. A finite compute budget. Every model, failure and breakthrough persists.</p><label>Company name<input id="companyName" value="Nova Frontier"></label><label>Model family prefix<input id="modelPrefix" value="NOVA" maxlength="10"></label><button class="primary huge" onclick="foundLab()">Found the lab →</button><div class="truth">Simulation values are derived where possible. Teaching approximations are labeled and linked to primary sources.</div></div></div>`}
function campusScene(){const racks=Math.min(14,2+state.infra*2);return `<div class="campus-scene infra-${state.infra}"><div class="sky-glow"></div><div class="building research-b"><span>RESEARCH</span><i></i><i></i><i></i></div><div class="building data-b"><span>DATA</span><i></i><i></i></div><div class="gpu-hall"><span>GPU HALL</span><div class="racks">${Array.from({length:racks},(_,i)=>`<i class="rack" style="--i:${i}"></i>`).join("")}</div></div><div class="network-line a"></div><div class="network-line b"></div><div class="satellite">◈</div>${state.activeRun?`<div class="data-flow">${Array.from({length:8},(_,i)=>`<i style="--i:${i}"></i>`).join("")}</div>`:""}</div>`}
function launchPanel(){return `<p class="lead">Choose the next model in your lineage. Larger runs require infrastructure and research—not just money.</p><div class="tier-grid">${MODEL_TIERS.map(t=>{const p=trainingPhysics(t),ok=tierAvailable(t);return `<button class="tier ${ok?"":"locked"}" ${ok?`onclick="launchTier('${t.id}')"`:"disabled"}><span>${t.name}</span><b>${fmt(t.paramsB,2)}B params</b><em>${fmt(p.tokens/1e9,0)}B tokens · ${fmt(p.gpuHours,0)} H100h</em><small>${ok?`${money(t.costM)} launch budget`:`Requires infra ${t.minInfra}${t.requires?` + ${t.requires}`:""}`}</small></button>`}).join("")}</div>`}
function runPanel(r){const p=r.physics,currentStep=Math.floor(p.steps*r.progress/100),tokens=currentStep*p.batch;return `<div class="run-progress"><div class="progress-head"><b>${r.phase.toUpperCase()}</b><span>${r.progress}%</span></div><div class="bigbar"><i style="width:${r.progress}%"></i></div></div><div class="telemetry-grid"><div><span>Optimizer step</span><b>${fmt(currentStep,0)} / ${fmt(p.steps,0)}</b></div><div><span>Tokens seen</span><b>${fmt(tokens/1e9,2)}B</b></div><div><span>Global batch</span><b>${fmt(p.batch/1e6,3)}M tok</b></div><div><span>Train loss</span><b>${r.loss.toFixed(3)}</b></div><div><span>${termButton("FLOPS")}</span><b>${p.flops.toExponential(2)}</b></div><div><span>Compute charged</span><b>${fmt(p.gpuHours,0)} H100h</b></div></div><div class="sparkline">${Array.from({length:28},(_,i)=>`<i style="height:${Math.max(8,78-i*2+Math.sin(i*1.6)*9)}%"></i>`).join("")}</div>${r.incident?`<button class="danger-btn" onclick="openIncident('${r.incident}')">🔴 Investigate engineering incident</button>`:`<button class="primary" onclick="advanceRun()">Advance training →</button>`}<p class="sim-note">tokens seen = optimizer steps × global batch tokens. FLOPs uses the labeled dense-transformer teaching approximation.</p>`}
function lineage(){if(!state.models.length)return `<div class="empty-model"><div class="ghost-model">◇</div><p>Your first trained model will appear here permanently.</p></div>`;return `<div class="lineage">${state.models.map((m,i)=>`<div class="model-node"><div class="orb">${i+1}</div><div><b>${esc(m.name)}</b><span>${m.tier}</span><small>${fmt(m.tokensB,1)}B tokens · ${fmt(m.steps,0)} steps · score ${m.score}</small></div></div>`).join(`<div class="line"></div>`)}</div>`}
function techTree(){return `<div class="tech-tree">${TECH_TREE.map(t=>{const done=hasTech(t.id),ready=t.requires.every(x=>hasTech(x));return `<div class="tech-wrap"><button class="tech-node ${done?"done":ready?"ready":"locked"}" ${done||!ready?"disabled":`onclick="researchTech('${t.id}')"`}><div>${done?"✓":"◈"}</div><b>${t.name}</b><span>${t.effect}</span><small>${done?"Unlocked":ready?`${t.cost} insight`:"Requires "+t.requires.join(" + ")}</small></button><button class="tech-help" onclick="showExplain('${t.term}')">${t.term} ?</button></div>`}).join("")}</div>`}
function knowledgePanel(){const keys=["GRAD","PP","CONTAM","TTFT","DPO","FSDP","FP8","FLASH"];return `<div class="knowledge">${keys.map(k=>{const v=Math.min(6,state.knowledge[k]||0);return `<div><button onclick="showExplain('${k}')">${k}</button><span>${Array.from({length:6},(_,i)=>`<i class="${i<v?"on":""}"></i>`).join("")}</span><em>${["Unseen","Seen","Explained","Applied","Diagnosed","Transferred","Mastered"][v]}</em></div>`}).join("")}</div>`}
function incidentOverlay(){const inc=INCIDENTS.find(x=>x.id===state.selectedIncident);if(!inc)return"";const items=inc.tabs[state.incidentTab]||[];return `<div class="incident-back"><div class="incident"><div class="incident-head"><div><div class="eyebrow">LIVE ENGINEERING INCIDENT · ${inc.role}</div><h2>${inc.title}</h2><p>${inc.brief}</p></div><div class="alarm">!</div></div><div class="inspect-tabs">${["metrics","systems","data"].map(t=>`<button class="${state.incidentTab===t?"active":""}" onclick="inspectTab('${t}')">${t}</button>`).join("")}</div><div class="evidence">${items.map(x=>`<div><span>›</span>${esc(x)}</div>`).join("")}</div><div class="decision"><div class="eyebrow">MAKE THE CALL</div><h3>What do you do?</h3>${inc.choices.map(c=>`<button onclick="solveIncident('${c[0]}')"><span>${esc(c[1])}</span><i>→</i></button>`).join("")}</div><div class="incident-tip">Need context? ${termButton(inc.term)} explains the concept without revealing the answer.</div></div></div>`}
function render(){const app=document.getElementById("app");if(!state.started){app.innerHTML=founderScreen();return}const r=state.activeRun;app.innerHTML=`<div class="game-shell"><header class="hud"><div><div class="eyebrow">${infraName()}</div><h1>${esc(state.company)}</h1><div class="sub">Model family <b>${esc(state.prefix)}</b> · Day ${state.day} · ${state.employees} people</div></div><div class="resource-strip"><div><span>Cash</span><b>${money(state.cashM)}</b></div><div><span>Compute</span><b>${fmt(state.compute,0)} H100h</b></div><div><span>Reputation</span><b>${state.reputation}</b></div><div><span>Insight</span><b>${state.research}</b></div></div></header><nav class="rolebar">${ROLES.map(x=>`<button class="${state.role===x?"active":""}" onclick='switchRole(${JSON.stringify(x)})'>${x.replace(" Engineer","")}</button>`).join("")}</nav><main class="world-grid"><section class="campus panel"><div class="panel-title"><div><div class="eyebrow">LIVE COMPANY</div><h2>${infraName()}</h2></div><button class="ghost" onclick="upgradeInfra()">Expand campus</button></div>${campusScene()}<div class="ticker"><span class="pulse"></span>${esc(state.feed[0]||"All systems nominal")}</div></section><section class="run panel"><div class="panel-title"><div><div class="eyebrow">TRAINING OPERATIONS</div><h2>${r?esc(r.name):"No active training run"}</h2></div>${r?`<div class="status ${r.incident?"danger":"live"}">${r.incident?"INCIDENT":"LIVE"}</div>`:""}</div>${r?runPanel(r):launchPanel()}</section><section class="models panel"><div class="panel-title"><div><div class="eyebrow">MODEL LINEAGE</div><h2>Your models</h2></div><span class="counter">${state.models.length}</span></div>${lineage()}</section><section class="tech panel"><div class="panel-title"><div><div class="eyebrow">RESEARCH TREE</div><h2>Technology</h2></div><span class="counter">${state.tech.length}/${TECH_TREE.length}</span></div>${techTree()}</section><section class="career panel"><div class="panel-title"><div><div class="eyebrow">ENGINEERING MASTERY</div><h2>Your knowledge model</h2></div></div>${knowledgePanel()}</section><section class="feedpanel panel"><div class="panel-title"><div><div class="eyebrow">LAB HISTORY</div><h2>Company log</h2></div><button class="ghost" onclick="resetGame()">Reset</button></div><div class="feed">${state.feed.map(x=>`<div>${esc(x)}</div>`).join("")}</div></section></main></div><div id="modalRoot"></div>${state.selectedIncident?incidentOverlay():""}`}
render();