// Phase 4D.13 — Governance Conflicts, Board Votes & Founder-Control Risk
const GOVERNANCE_VERSION=1;
const BOARD_MOTIONS={
  runway:{name:'Approve emergency financing',type:'financing',founderBias:.2,investorBias:.85,strategicBias:.55,requiresVeto:true},
  accelerate:{name:'Accelerate frontier roadmap',type:'strategy',founderBias:.8,investorBias:.48,strategicBias:.65,requiresVeto:false},
  reliability:{name:'Pause launches for reliability',type:'reliability',founderBias:.5,investorBias:.62,strategicBias:.75,requiresVeto:false},
  sale:{name:'Authorize strategic sale process',type:'sale',founderBias:.25,investorBias:.88,strategicBias:.7,requiresVeto:true},
  ceo_review:{name:'Open CEO confidence review',type:'leadership',founderBias:.05,investorBias:.8,strategicBias:.65,requiresVeto:false}
};
function ensureGovernanceState(){ensureMacroState?.();state.governance ||= {version:GOVERNANCE_VERSION,motions:[],history:[],founderAuthority:.78,ceoStatus:'active',vetoes:0,crisisLeadership:0,nextMotionId:1};}
function governanceBoard(){ensureGovernanceState();const b=state.financing?.board||{founder:2,investor:1,strategic:0};return {founder:b.founder||0,investor:b.investor||0,strategic:b.strategic||0,total:(b.founder||0)+(b.investor||0)+(b.strategic||0)}}
function founderControlRisk(){ensureGovernanceState();const board=governanceBoard(),equity=state.financing?.capTable?.founders??.5,authority=state.governance.founderAuthority;const boardShare=board.total?board.founder/board.total:1;const risk=Math.max(0,Math.min(1,.5*(1-equity)+.35*(1-boardShare)+.15*(1-authority)));return {risk,equity,boardShare,authority,status:risk>.68?'critical':risk>.45?'fragile':'stable'} }
function motionSupport(kind,seat){const m=BOARD_MOTIONS[kind];let base=seat==='founder'?m.founderBias:seat==='investor'?m.investorBias:m.strategicBias;const runway=typeof quarterlyRunwayMonths==='function'?quarterlyRunwayMonths():12;const rel=state.roadmapPressure?.stakeholder?.reliability??.7;if(kind==='runway'&&runway<4)base+=.15;if(kind==='reliability'&&rel<.55)base+=.15;if(kind==='ceo_review'&&state.quarterly?.boardConfidence<.45)base+=.18;if(kind==='sale'&&runway<3)base+=.15;return Math.max(0,Math.min(1,base))}
function callBoardVote(kind){ensureGovernanceState();const m=BOARD_MOTIONS[kind];if(!m)return;const board=governanceBoard(),votes={yes:0,no:0,abstain:0,detail:[]};['founder','investor','strategic'].forEach(seat=>{for(let i=0;i<board[seat];i++){const p=motionSupport(kind,seat),seed=((state.day||1)*31+(state.governance.nextMotionId||1)*17+i*7+seat.length*11)%100/100;const vote=seed<p?'yes':seed>Math.min(.98,p+.12)?'no':'abstain';votes[vote]++;votes.detail.push({seat,vote,p})}});const investorNo=votes.detail.some(v=>v.seat==='investor'&&v.vote==='no'),veto=m.requiresVeto&&investorNo&&(state.financing?.covenantPressure||0)>.2;const passed=!veto&&votes.yes>votes.no;const id=`BV-${String(state.governance.nextMotionId++).padStart(3,'0')}`;const rec={id,day:state.day||1,kind,name:m.name,votes,passed,veto};state.governance.motions.push(rec);if(veto)state.governance.vetoes++;applyBoardOutcome(rec);state.governance.history.push({day:state.day||1,type:'board.vote',id,kind,passed,veto});save();render()}
function applyBoardOutcome(rec){const g=state.governance;if(rec.veto){g.founderAuthority=Math.max(0,g.founderAuthority-.06);state.quarterly.boardConfidence=Math.max(0,state.quarterly.boardConfidence-.03);log?.(`🛑 Investor veto blocked ${rec.name}.`);return}if(!rec.passed){g.founderAuthority=Math.max(0,g.founderAuthority-.025);log?.(`❌ Board rejected ${rec.name}.`);return}switch(rec.kind){case'runway':state.quarterly.investorPatience=Math.min(1,state.quarterly.investorPatience+.06);break;case'accelerate':state.roadmapPressure.executive.pressure=Math.min(1,state.roadmapPressure.executive.pressure+.12);state.roadmapPressure.stakeholder.reliability=Math.max(0,state.roadmapPressure.stakeholder.reliability-.04);break;case'reliability':Object.values(state.slo?.components||{}).forEach(c=>c.budgetRemaining=Math.min(1,(c.budgetRemaining??1)+.04));state.roadmapPressure.stakeholder.reliability=Math.min(1,state.roadmapPressure.stakeholder.reliability+.05);break;case'sale':generateAcquisitionOffer?.();break;case'ceo_review':resolveCeoReview();break}g.founderAuthority=Math.min(1,g.founderAuthority+.015);log?.(`✅ Board approved ${rec.name}.`)}
function resolveCeoReview(){ensureGovernanceState();const g=state.governance,runway=typeof quarterlyRunwayMonths==='function'?quarterlyRunwayMonths():12,confidence=state.quarterly?.boardConfidence??.7,cred=state.roadmapPressure?.executive?.credibility??.7,score=.4*confidence+.3*cred+.3*Math.min(1,runway/9);if(score<.42){g.ceoStatus='removed';g.founderAuthority=Math.max(0,g.founderAuthority-.28);state.quarterly.investorPatience=Math.min(1,state.quarterly.investorPatience+.08);state.companyLeadership={role:'CEO',status:'board-appointed',day:state.day||1};log?.('⚠ Board removed the founder from the CEO role.')}else{g.ceoStatus='retained';g.crisisLeadership++;g.founderAuthority=Math.min(1,g.founderAuthority+.08);state.quarterly.boardConfidence=Math.min(1,state.quarterly.boardConfidence+.04);log?.('🧭 CEO retained after board confidence review.')}}
function declareFiduciaryPriority(priority){ensureGovernanceState();const g=state.governance;if(priority==='survival'){state.quarterly.investorPatience=Math.min(1,state.quarterly.investorPatience+.05);state.roadmapPressure.stakeholder.product=Math.max(0,state.roadmapPressure.stakeholder.product-.03);g.founderAuthority=Math.max(0,g.founderAuthority-.02)}else if(priority==='mission'){state.roadmapPressure.stakeholder.product=Math.min(1,state.roadmapPressure.stakeholder.product+.04);state.quarterly.investorPatience=Math.max(0,state.quarterly.investorPatience-.04);g.founderAuthority=Math.min(1,g.founderAuthority+.03)}else{state.quarterly.boardConfidence=Math.min(1,state.quarterly.boardConfidence+.025)}g.history.push({day:state.day||1,type:'fiduciary.priority',priority});save();render()}
function governanceOpen(){ensureGovernanceState();state.view='governance';save();render()}
function governanceClose(){state.view='company';save();render()}
function renderGovernance(){ensureGovernanceState();const g=state.governance,b=governanceBoard(),r=founderControlRisk();return `<div class="gv-shell"><header class="gv-head"><div><div class="eyebrow">PHASE 4D.13 · GOVERNANCE</div><h1>Board Votes, Founder Control & Crisis Leadership</h1><p>Capital structure now changes who can actually decide. Call board votes, navigate vetoes, choose fiduciary priorities, and survive confidence reviews.</p></div><button onclick="governanceClose()">Return to company</button></header><section class="gv-summary"><div><span>Founder control risk</span><b>${Math.round(r.risk*100)}%</b><small>${r.status}</small></div><div><span>Founder authority</span><b>${Math.round(g.founderAuthority*100)}%</b></div><div><span>Board</span><b>${b.founder}/${b.investor}/${b.strategic}</b><small>founder / investor / strategic</small></div><div><span>CEO status</span><b>${esc(g.ceoStatus)}</b></div></section><section class="gv-card"><h2>Board motions</h2><div class="gv-grid">${Object.entries(BOARD_MOTIONS).map(([k,m])=>`<article><b>${esc(m.name)}</b><span>${esc(m.type)}${m.requiresVeto?' · investor veto-sensitive':''}</span><button onclick="callBoardVote('${k}')">Call vote</button></article>`).join('')}</div></section><section class="gv-card"><h2>Fiduciary posture</h2><button onclick="declareFiduciaryPriority('survival')">Prioritize survival/runway</button><button onclick="declareFiduciaryPriority('mission')">Prioritize frontier mission</button><button onclick="declareFiduciaryPriority('balanced')">Balance stakeholders</button></section><section class="gv-card"><h2>Recent votes</h2>${g.motions.slice().reverse().map(v=>`<div class="gv-row ${v.passed?'pass':'fail'}"><div><b>${esc(v.name)}</b><span>${v.id} · ${v.votes.yes} yes / ${v.votes.no} no / ${v.votes.abstain} abstain${v.veto?' · VETOED':''}</span></div><b>${v.passed?'PASSED':'FAILED'}</b></div>`).join('')||'<p>No board votes yet.</p>'}</section></div>`}
const governanceBaseRender=render;render=function(){ensureGovernanceState();if(state.view==='governance'){document.getElementById('app').innerHTML=renderGovernance();return}governanceBaseRender();if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const r=founderControlRisk(),b=document.createElement('button');b.className='gv-launch';b.onclick=governanceOpen;b.innerHTML=`<span>BOARD GOVERNANCE</span><b>${Math.round(r.risk*100)}% founder-control risk · ${esc(state.governance.ceoStatus)}</b><small>Votes · vetoes · CEO confidence · fiduciary choices →</small>`;shell.insertBefore(b,shell.children[1]||null)};render();