// Phase 4B.4 — Hiring + Org Design
const HIRING_VERSION=1;
const CANDIDATE_POOL=[
  {id:'amina',name:'Amina Yusuf',role:'Research Engineer',level:'Senior',avatar:'AY',color:'violet',specialty:'Optimization research',team:'Research',compK:610,skills:{training:8,research:8,distributed:5,evals:5,data:4,inference:3,post:6,safety:3},traits:['Fast experimental loop','Needs strong systems partners']},
  {id:'theo',name:'Theo Martin',role:'Distributed Systems Engineer',level:'Staff',avatar:'TM',color:'cyan',specialty:'Large-scale training',team:'Pretraining',compK:720,skills:{distributed:9,nccl:9,training:8,inference:5,data:2,evals:2,post:2,safety:2},traits:['Deep cluster expertise','Expensive hire']},
  {id:'mei',name:'Mei Tanaka',role:'Inference Engineer',level:'Senior',avatar:'MT',color:'green',specialty:'Serving efficiency',team:'Inference',compK:590,skills:{inference:9,distributed:6,training:4,evals:4,data:3,post:3,safety:3},traits:['Strong production instincts','Less research depth']},
  {id:'dev',name:'Dev Raman',role:'Data Quality Engineer',level:'Senior',avatar:'DR',color:'amber',specialty:'Data provenance',team:'Data',compK:540,skills:{data:9,evals:8,training:5,distributed:2,inference:2,post:5,safety:5},traits:['Excellent contamination intuition','Conservative about risky launches']},
  {id:'lucia',name:'Lucia Moretti',role:'Safety Research Engineer',level:'Senior',avatar:'LM',color:'red',specialty:'Behavioral robustness',team:'Safety',compK:560,skills:{safety:9,evals:8,post:7,data:5,training:4,inference:2,distributed:2},traits:['Strong red-team mindset','Pushes for slower release gates']},
  {id:'owen',name:'Owen Price',role:'Infrastructure Engineer',level:'Senior',avatar:'OP',color:'blue',specialty:'GPU fleet reliability',team:'Infrastructure',compK:575,skills:{distributed:8,nccl:8,inference:6,training:5,data:2,evals:2,post:2,safety:2},traits:['Operationally disciplined','Prefers reliability over novelty']}
];
const ORG_TEAMS=['Research','Pretraining','Data','Post-Training','Inference','Evals','Safety','Infrastructure'];
function ensureHiring(){
  if(typeof ensureCareerState==='function')ensureCareerState();
  state.hiring ||= {version:HIRING_VERSION,headcountBudget:14,annualCompBudgetK:8200,candidates:CANDIDATE_POOL.map(c=>({...c,status:'available',interview:null,offer:null})),teams:{},selectedCandidateId:'amina',selectedEmployeeId:'maya',rivalPressure:0,nextEventId:1};
  state.hiring.candidates ||= CANDIDATE_POOL.map(c=>({...c,status:'available',interview:null,offer:null}));
  state.hiring.teams ||= {};
  ORG_TEAMS.forEach(t=>state.hiring.teams[t] ||= {name:t,managerId:null,memberIds:[]});
  for(const e of state.npcEmployees||[]){if(!e.orgTeam)e.orgTeam=inferTeam(e);if(!e.compK)e.compK=defaultComp(e);const team=state.hiring.teams[e.orgTeam]||state.hiring.teams.Research;if(team&&!team.memberIds.includes(e.id))team.memberIds.push(e.id)}
  syncManagers();syncAttritionRisk();
}
function inferTeam(e){const b=e.bias;return b==='systems'?'Pretraining':b==='data'?'Data':b==='post'?'Post-Training':b==='inference'?'Inference':b==='evals'?'Evals':b==='safety'?'Safety':b==='infra'?'Infrastructure':'Research'}
function defaultComp(e){const byLevel={'Engineer I':260,'Engineer II':330,'Senior':480,'Staff':620,'Principal':800,'Distinguished':1050};return byLevel[e.career?.level||e.level]||480}
function currentCompK(){ensureHiring();return (state.npcEmployees||[]).reduce((s,e)=>s+(e.compK||defaultComp(e)),0)}
function headcountUsed(){return state.npcEmployees?.length||0}
function hiringCapacity(){return {headcountLeft:Math.max(0,state.hiring.headcountBudget-headcountUsed()),compLeftK:Math.max(0,state.hiring.annualCompBudgetK-currentCompK())}}
function interviewCandidate(id){ensureHiring();const c=state.hiring.candidates.find(x=>x.id===id);if(!c||c.status!=='available')return;const technical=Math.min(100,50+Math.round(Object.values(c.skills).reduce((a,b)=>a+b,0)*.7));const collaboration=55+((c.id.length*13+state.day*3)%35);const judgment=50+((c.name.length*7+state.day*5)%40);const score=Math.round(technical*.5+collaboration*.25+judgment*.25);c.interview={day:state.day,technical,collaboration,judgment,score,recommendation:score>=82?'strong hire':score>=72?'hire':score>=62?'mixed':'no hire'};c.status='interviewed';state.day++;save();render()}
function extendOffer(id,premium=0){ensureHiring();const c=state.hiring.candidates.find(x=>x.id===id);if(!c||!c.interview)return;const cap=hiringCapacity(),offerK=Math.round(c.compK*(1+premium));if(cap.headcountLeft<1||cap.compLeftK<offerK){c.offer={status:'blocked',offerK,reason:cap.headcountLeft<1?'No headcount remaining':'Compensation budget exceeded'};save();render();return}const quality=c.interview.score+(premium>0?7:0)-Math.round(state.hiring.rivalPressure/8);const accepted=quality>=68;c.offer={status:accepted?'accepted':'declined',offerK,premium,day:state.day};if(accepted)hireCandidate(c);else c.status='declined';save();render()}
function hireCandidate(c){const e={id:`hire-${c.id}`,name:c.name,role:c.role,level:c.level,avatar:c.avatar,color:c.color,specialty:c.specialty,bio:`Hired into ${c.team} after a structured interview.`,skills:{...c.skills},bias:c.team==='Pretraining'?'systems':c.team==='Infrastructure'?'infra':c.team==='Post-Training'?'post':c.team.toLowerCase(),trait:c.traits[0],trust:52,respect:54,alignment:55,workload:18,memories:[],ideasGenerated:0,incidentsHelped:0,discoveries:[],orgTeam:c.team,compK:c.offer.offerK};if(typeof careerDefaults==='function')careerDefaults(e);state.npcEmployees.push(e);state.hiring.teams[c.team].memberIds.push(e.id);c.status='hired';npcRemember?.(e,`Joined ${state.company} on day ${state.day}.`,'career');log(`👤 Hired ${c.name} into ${c.team}.`)}
function assignEmployeeTeam(employeeId,teamName){ensureHiring();const e=npcById(employeeId);const team=state.hiring.teams[teamName];if(!e||!team)return;ORG_TEAMS.forEach(t=>state.hiring.teams[t].memberIds=state.hiring.teams[t].memberIds.filter(id=>id!==employeeId));team.memberIds.push(employeeId);e.orgTeam=teamName;e.relationships.autonomy=Math.min(100,e.relationships.autonomy+1);save();render()}
function setTeamManager(teamName,employeeId){ensureHiring();const team=state.hiring.teams[teamName],e=npcById(employeeId);if(!team||!e)return;team.managerId=employeeId;e.leadershipSkills.communication=Math.min(10,e.leadershipSkills.communication+.15);e.relationships.autonomy=Math.min(100,e.relationships.autonomy+3);save();render()}
function syncManagers(){for(const t of Object.values(state.hiring.teams||{})){if(t.managerId&&!state.npcEmployees.some(e=>e.id===t.managerId))t.managerId=null;if(!t.managerId){const candidates=t.memberIds.map(id=>npcById(id)).filter(Boolean).sort((a,b)=>(b.leadershipSkills?.technicalJudgment||0)-(a.leadershipSkills?.technicalJudgment||0));if(candidates[0]&&['Staff','Principal','Distinguished'].includes(candidates[0].career?.level||candidates[0].level))t.managerId=candidates[0].id}}}
function syncAttritionRisk(){for(const e of state.npcEmployees||[]){careerDefaults?.(e);const w=e.workloadState?.current||e.workload||20,aut=e.relationships?.autonomy||55,trust=e.relationships?.trust||55;const compPenalty=(e.compK||defaultComp(e))<defaultComp(e)*.9?12:0;e.attritionRisk=Math.max(2,Math.min(85,Math.round(8+Math.max(0,w-65)*.7+Math.max(0,50-aut)*.5+Math.max(0,50-trust)*.35+compPenalty+state.hiring.rivalPressure*.15)))}}
function simulateRecruitingPressure(){ensureHiring();state.hiring.rivalPressure=Math.min(100,state.hiring.rivalPressure+8+((state.day*7)%9));for(const e of state.npcEmployees||[]){if((e.attritionRisk||0)>=45&&!(e.career.externalOffers||[]).some(o=>!o.resolved)){e.career.externalOffers.push({id:`EXT-${state.hiring.nextEventId++}`,day:state.day,lab:['Helix AI','NovaMind','Axiom Research'][state.day%3],premiumPct:15+state.day%16,resolved:false})}}save();render()}
function retainEmployee(id,choice){const e=npcById(id),offer=e?.career?.externalOffers?.find(o=>!o.resolved);if(!e||!offer)return;if(choice==='counter'){e.compK=Math.round(e.compK*(1+offer.premiumPct/100*.65));e.relationships.trust=Math.min(100,e.relationships.trust+4);e.attritionRisk=Math.max(5,e.attritionRisk-18)}else if(choice==='ownership'){e.relationships.autonomy=Math.min(100,e.relationships.autonomy+12);e.relationships.trust=Math.min(100,e.relationships.trust+3);e.attritionRisk=Math.max(5,e.attritionRisk-15)}else if(choice==='leave'){state.npcEmployees=state.npcEmployees.filter(x=>x.id!==id);ORG_TEAMS.forEach(t=>state.hiring.teams[t].memberIds=state.hiring.teams[t].memberIds.filter(x=>x!==id));log(`↗ ${e.name} left for ${offer.lab}.`)}offer.resolved=choice;save();render()}
function hiringOpen(){ensureHiring();state.view='hiring';save();render()}
function hiringClose(){state.view='company';save();render()}
function hiringSelectCandidate(id){state.hiring.selectedCandidateId=id;save();render()}
function orgChart(){return ORG_TEAMS.map(name=>{const t=state.hiring.teams[name],m=npcById(t.managerId);const members=t.memberIds.map(id=>npcById(id)).filter(Boolean);return `<section class="org-team"><header><div><b>${esc(name)}</b><span>${members.length} people</span></div><em>${m?`Lead: ${esc(m.name)}`:'No manager'}</em></header>${members.map(e=>`<div class="org-person"><span class="npc-avatar mini ${e.color}">${esc(e.avatar)}</span><div><b>${esc(e.name)}</b><small>${esc(e.career?.level||e.level)} · ${esc(e.specialty)}</small></div><i>${e.attritionRisk||0}% risk</i></div>`).join('')||'<p>Empty team</p>'}<div class="org-manager">${members.map(e=>`<button onclick="setTeamManager('${name}','${e.id}')">Make ${esc(e.name.split(' ')[0])} lead</button>`).join('')}</div></section>`}).join('')}
function candidateCard(c){return `<article class="candidate ${c.status}"><header><div class="npc-avatar ${c.color}">${esc(c.avatar)}</div><div><b>${esc(c.name)}</b><span>${esc(c.level)} · ${esc(c.role)}</span></div><em>$${c.compK}K</em></header><p>${esc(c.specialty)} · ${esc(c.traits.join(' · '))}</p>${c.interview?`<div class="interview"><div><span>Technical</span><b>${c.interview.technical}</b></div><div><span>Collaboration</span><b>${c.interview.collaboration}</b></div><div><span>Judgment</span><b>${c.interview.judgment}</b></div><strong>${esc(c.interview.recommendation)}</strong></div>`:''}<footer>${c.status==='available'?`<button onclick="interviewCandidate('${c.id}')">Interview</button>`:c.status==='interviewed'?`<button onclick="extendOffer('${c.id}',0)">Standard offer</button><button onclick="extendOffer('${c.id}',.12)">Strong offer +12%</button>`:c.offer?`<span>${esc(c.offer.status)}${c.offer.offerK?` · $${c.offer.offerK}K`:''}</span>`:`<span>${esc(c.status)}</span>`}</footer></article>`}
function renderHiring(){ensureHiring();const cap=hiringCapacity(),offers=(state.npcEmployees||[]).filter(e=>e.career?.externalOffers?.some(o=>!o.resolved));return `<div class="hiring-shell"><header class="hiring-head"><div><div class="eyebrow">PHASE 4B.4 · HIRING + ORG DESIGN</div><h1>Build the lab, not just the model.</h1><p>Interview candidates, manage compensation and headcount, assign teams and leads, and defend the organization from rival recruiting pressure.</p></div><button onclick="hiringClose()">Return to company</button></header><section class="hiring-budget"><div><span>Headcount</span><b>${headcountUsed()} / ${state.hiring.headcountBudget}</b></div><div><span>Annual comp</span><b>$${currentCompK()}K / $${state.hiring.annualCompBudgetK}K</b></div><div><span>Headcount left</span><b>${cap.headcountLeft}</b></div><div><span>Recruiting pressure</span><b>${state.hiring.rivalPressure}%</b></div><button onclick="simulateRecruitingPressure()">Advance recruiting market</button></section>${offers.length?`<section class="rival-offers"><div class="eyebrow">RIVAL OFFERS</div>${offers.map(e=>{const o=e.career.externalOffers.find(x=>!x.resolved);return `<article><div><b>${esc(e.name)}</b><p>${esc(o.lab)} offered +${o.premiumPct}% compensation.</p></div><div><button onclick="retainEmployee('${e.id}','counter')">Counter</button><button onclick="retainEmployee('${e.id}','ownership')">Offer ownership</button><button onclick="retainEmployee('${e.id}','leave')">Let leave</button></div></article>`}).join('')}</section>`:''}<div class="hiring-layout"><section><div class="eyebrow">CANDIDATE PIPELINE</div><h2>Recruiting</h2><div class="candidate-grid">${state.hiring.candidates.map(candidateCard).join('')}</div></section><section><div class="eyebrow">ORG CHART</div><h2>Teams & leadership</h2><div class="org-chart">${orgChart()}</div></section></div></div>`}
const hiringRender=render;
render=function(){ensureHiring();if(state.view==='hiring'){document.getElementById('app').innerHTML=renderHiring();return}hiringRender();if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const b=document.createElement('button');b.className='hiring-launch';b.onclick=hiringOpen;b.innerHTML=`<span>HIRING + ORG</span><b>${headcountUsed()} employees · ${hiringCapacity().headcountLeft} slots left</b><small>Recruit · structure · retain →</small>`;shell.insertBefore(b,shell.children[5]||null)};
render();
