// Phase 4B.3B — Organizational Knowledge
const ORG_KNOWLEDGE_VERSION=1;
const KNOWLEDGE_LEVELS=[['tentative',1],['supported',2],['strong',4],['institutionalized',7]];
function ensureKnowledgeState(){
  ensureOrgHistory?.();
  state.organization.knowledge ||= [];
  state.organization.standards ||= [];
  state.organization.knowledgeVersion ||= ORG_KNOWLEDGE_VERSION;
  state.organization.nextKnowledgeId ||= 1;
  state.organization.nextStandardId ||= 1;
  state.organization.reliability ||= {detection:{},recurrence:{}};
}
function knowledgeDomain(type){return ({nan:'training',bubble:'distributed',contam:'evals',ttft:'inference',dpo:'post'})[type]||'training'}
function lessonTemplate(type){const m={
  nan:{title:'Shard-local failures should be replayed before global optimizer changes',lesson:'When a training failure begins exactly at a shard boundary and reproduces on a small replay, isolate the data path before changing global optimization settings.'},
  bubble:{title:'Pipeline degree must scale with useful in-flight microbatches',lesson:'Increasing pipeline parallelism can reduce MFU when fill/drain bubbles grow faster than useful in-flight work.'},
  contam:{title:'Large isolated eval jumps require provenance and overlap checks',lesson:'When one benchmark jumps far beyond controls after a data refresh, treat train/eval overlap as a live hypothesis until provenance and decontaminated holdouts are verified.'},
  ttft:{title:'TTFT and decode latency must be diagnosed separately',lesson:'When TTFT degrades while inter-token latency stays healthy, queued prefill and routing pressure are more informative than generic decode optimization.'},
  dpo:{title:'Post-training releases need slice-level gates',lesson:'Aggregate preference gains can hide regressions in tool exactness, refusals, and other product-critical slices; release decisions must remain multi-objective.'}
};return m[type]||{title:'Incident lesson',lesson:'Use evidence from the resolved incident to improve future diagnosis and prevention.'}}
function evidenceSummaryForIncident(r){return (r.evidence||[]).map(x=>x.evidenceId).filter((v,i,a)=>a.indexOf(v)===i)}
function knowledgeConfidence(sources){const n=sources?.length||1;const level=[...KNOWLEDGE_LEVELS].reverse().find(x=>n>=x[1])?.[0]||'tentative';return {level,score:Math.min(.98,.48+n*.08)}}
function createKnowledgeFromIncident(r){
  ensureKnowledgeState();if(!r||state.organization.knowledge.some(k=>k.sourceRefs?.includes(r.id)))return null;
  const t=lessonTemplate(r.incidentType),similar=state.organization.knowledge.find(k=>k.domain===knowledgeDomain(r.incidentType)&&k.status==='active'&&k.title===t.title);
  if(similar){similar.sourceRefs.push(r.id);similar.modelIds=[...new Set([...(similar.modelIds||[]),r.modelId].filter(Boolean))];similar.contributors=[...new Set([...(similar.contributors||[]),...Object.keys(r.participants||{})])];similar.evidence=[...new Set([...(similar.evidence||[]),...evidenceSummaryForIncident(r)])];similar.confidence=knowledgeConfidence(similar.sourceRefs);similar.updatedDay=state.day;return similar}
  const k={id:`KN-${String(state.organization.nextKnowledgeId++).padStart(4,'0')}`,title:t.title,domain:knowledgeDomain(r.incidentType),lesson:t.lesson,status:'active',createdDay:state.day,updatedDay:state.day,confidence:knowledgeConfidence([r.id]),sourceRefs:[r.id],sourceTypes:['incident'],modelIds:[r.modelId].filter(Boolean),contributors:Object.keys(r.participants||{}),evidence:evidenceSummaryForIncident(r),hardwareContext:'current-lab',supersedes:null,supersededBy:null};state.organization.knowledge.push(k);return k;
}
function experimentKnowledge(){
  ensureKnowledgeState();const exps=state.modelLab?.experiments||[];for(const e of exps){if(e.status!=='complete'||!e.decision||e.decision==='reject')continue;const ref=`EXP-${e.id}`;if(state.organization.knowledge.some(k=>k.sourceRefs?.includes(ref)))continue;const m=state.models?.find(x=>x.id===e.modelId);state.organization.knowledge.push({id:`KN-${String(state.organization.nextKnowledgeId++).padStart(4,'0')}`,title:e.title,domain:'research',lesson:`${e.result}: ${e.observation||e.delta||'Experiment produced an actionable result.'}`,status:'active',createdDay:e.completedDay||state.day,updatedDay:state.day,confidence:knowledgeConfidence([ref]),sourceRefs:[ref],sourceTypes:['experiment'],modelIds:[m?.id].filter(Boolean),contributors:[],evidence:[e.delta].filter(Boolean),hardwareContext:'current-lab',supersedes:null,supersededBy:null})}}
function syncKnowledgeFromHistory(){ensureKnowledgeState();for(const r of state.organization.incidents||[])if(r.status==='resolved')createKnowledgeFromIncident(r);experimentKnowledge();promoteStandards();applyCorrectiveReliabilityEffects()}
function promoteStandards(){
  ensureKnowledgeState();for(const k of state.organization.knowledge){if(k.status!=='active'||k.confidence.level!=='institutionalized'||state.organization.standards.some(s=>s.knowledgeId===k.id))continue;state.organization.standards.push({id:`STD-${String(state.organization.nextStandardId++).padStart(3,'0')}`,knowledgeId:k.id,title:k.title,domain:k.domain,createdDay:state.day,status:'active',effect:'Applies this institutional lesson to future runs and incident triage.'})}}
function applyCorrectiveReliabilityEffects(){
  ensureKnowledgeState();const completed=(state.organization.actionItems||[]).filter(a=>a.status==='complete');const detection={},recurrence={};
  for(const a of completed){const inc=state.organization.incidents.find(r=>r.id===a.incidentId);if(!inc)continue;const t=inc.incidentType;const text=(a.effect||'').toLowerCase();if(text.includes('detect')||text.includes('earlier')||text.includes('dashboard')||text.includes('alert'))detection[t]=(detection[t]||0)+.2;else recurrence[t]=(recurrence[t]||0)+.15}
  state.organization.reliability.detection=detection;state.organization.reliability.recurrence=recurrence;
}
function knowledgeRelevance(type,k){if(k.status!=='active')return 0;let s=0;if(k.domain===knowledgeDomain(type))s+=60;if(k.sourceRefs?.some(ref=>state.organization.incidents.find(r=>r.id===ref)?.incidentType===type))s+=30;s+=(k.confidence?.score||0)*10;return s}
function relatedKnowledge(type,limit=4){syncKnowledgeFromHistory();return state.organization.knowledge.map(k=>[k,knowledgeRelevance(type,k)]).filter(x=>x[1]>20).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(x=>x[0])}
function knowledgeStaleness(k){const age=(state.day||1)-(k.updatedDay||k.createdDay||1);if(k.status==='superseded')return 'superseded';if(age>150)return 'possibly stale';return 'current'}
function supersedeKnowledge(oldId,newId){ensureKnowledgeState();const old=state.organization.knowledge.find(k=>k.id===oldId),next=state.organization.knowledge.find(k=>k.id===newId);if(!old||!next||old.id===next.id)return;old.status='superseded';old.supersededBy=next.id;next.supersedes=old.id;save();render()}
function openKnowledgeBase(){syncKnowledgeFromHistory();state.view='knowledge';save();render()}
function closeKnowledgeBase(){state.view='company';save();render()}
function renderKnowledgeCard(k){const sources=(k.sourceRefs||[]).map(ref=>{const r=state.organization.incidents.find(x=>x.id===ref);return r?`${ref} · ${r.title}`:ref}).join(' · ');return `<article class="kb-card"><header><div><span>${esc(k.id)} · ${esc(k.domain)}</span><h2>${esc(k.title)}</h2></div><em class="${k.confidence.level}">${esc(k.confidence.level)}</em></header><p>${esc(k.lesson)}</p><div class="kb-meta"><span>Confidence ${Math.round(k.confidence.score*100)}%</span><span>${esc(knowledgeStaleness(k))}</span><span>${k.sourceRefs.length} source${k.sourceRefs.length===1?'':'s'}</span></div><details><summary>Provenance</summary><p><b>Sources:</b> ${esc(sources||'none')}</p><p><b>Models:</b> ${esc((k.modelIds||[]).join(', ')||'unlinked')}</p><p><b>Contributors:</b> ${esc((k.contributors||[]).map(id=>npcById?.(id)?.name||id).join(', ')||'none')}</p><p><b>Evidence:</b> ${esc((k.evidence||[]).join(', ')||'none')}</p></details>${k.status==='superseded'?`<small>Superseded by ${esc(k.supersededBy||'newer knowledge')}</small>`:''}</article>`}
function renderKnowledgeBase(){syncKnowledgeFromHistory();const active=state.organization.knowledge.filter(k=>k.status==='active'),old=state.organization.knowledge.filter(k=>k.status!=='active');const standards=state.organization.standards||[];return `<div class="kb-shell"><header class="kb-head"><div><div class="eyebrow">PHASE 4B.3B · ORGANIZATIONAL KNOWLEDGE</div><h1>Lab Knowledge Base</h1><p>Incidents and experiments now become provenance-backed lessons the lab can retrieve later.</p></div><button onclick="closeKnowledgeBase()">Return to company</button></header><main class="kb-main"><section class="kb-summary"><div><b>${active.length}</b><span>active lessons</span></div><div><b>${standards.length}</b><span>lab standards</span></div><div><b>${Object.keys(state.organization.reliability.detection||{}).length}</b><span>detection improvements</span></div></section>${standards.length?`<section class="kb-standards"><div class="eyebrow">LAB STANDARDS</div>${standards.map(s=>`<div><b>${esc(s.title)}</b><span>${esc(s.domain)} · ${esc(s.effect)}</span></div>`).join('')}</section>`:''}<section class="kb-grid">${active.length?active.map(renderKnowledgeCard).join(''):'<article class="kb-card empty"><h2>No lessons yet</h2><p>Resolve incidents or adopt experiment findings to create organizational knowledge.</p></article>'}</section>${old.length?`<section class="kb-archive"><div class="eyebrow">SUPERSEDED / ARCHIVED</div>${old.map(renderKnowledgeCard).join('')}</section>`:''}</main></div>`}
function renderRelatedKnowledgePanel(){if(!state.selectedIncident)return'';const rel=relatedKnowledge(state.selectedIncident);const d=state.organization.reliability.detection?.[state.selectedIncident]||0;return `<section class="kb-related"><div class="eyebrow">INTERNAL KNOWLEDGE</div><h3>What the lab already knows</h3>${d?`<p class="kb-alert">Completed corrective actions provide +${Math.round(d*100)}% simulated detection support for this incident family.</p>`:''}${rel.length?rel.map(k=>`<div><b>${esc(k.title)}</b><span>${esc(k.confidence.level)} · ${Math.round(k.confidence.score*100)}%</span><p>${esc(k.lesson)}</p></div>`).join(''):'<p>No relevant internal lesson has been established yet.</p>'}</section>`}
// Persist new lessons immediately after future incident resolution.
const kbSolveIncident=solveIncident;
solveIncident=function(id){const before=(state.organization?.incidents||[]).filter(r=>r.status==='resolved').length;const out=kbSolveIncident(id);const after=(state.organization?.incidents||[]).filter(r=>r.status==='resolved');if(after.length>before){createKnowledgeFromIncident(after.at(-1));syncKnowledgeFromHistory();save()}return out};
// Surface relevant internal knowledge directly in the workstation when available.
const kbRender=render;
render=function(){ensureKnowledgeState();syncKnowledgeFromHistory();if(state.view==='knowledge'){document.getElementById('app').innerHTML=renderKnowledgeBase();return}kbRender();if(state.selectedIncident){const host=document.querySelector('.ws-side,.workstation-sidebar,.workstation-grid');if(host&&!host.querySelector('.kb-related'))host.insertAdjacentHTML('beforeend',renderRelatedKnowledgePanel())}if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const b=document.createElement('button');b.className='kb-launch';b.onclick=openKnowledgeBase;b.innerHTML=`<span>KNOWLEDGE BASE</span><b>${state.organization.knowledge.length} lab lesson${state.organization.knowledge.length===1?'':'s'}</b><small>Provenance · standards · future incident retrieval →</small>`;shell.insertBefore(b,shell.children[3]||null)};
render();
