// Phase 4B.2 — Evidence-aware NPC beliefs and disagreement

const NPC_BELIEF_VERSION=1;
function ensureNpcBeliefs(){ensureNpcTeam();state.npcBeliefs ||= {version:NPC_BELIEF_VERSION,roundtableOpen:false};state.npcEmployees.forEach(e=>{e.beliefs ||= {};e.evidenceSeen ||= {};e.disagreements ||= 0})}
function beliefIncident(){return INCIDENTS.find(x=>x.id===state.selectedIncident)||null}
function initialBeliefs(e,inc){const c=WORKSTATION_CASES?.[inc.id];if(!c)return[];const d=incidentDomain(inc);return c.hypotheses.map(([id,label],i)=>{let score=25-i;if(id===c.correctHypothesis)score+=Math.max(0,(e.skills[d]||3)-5)*3;if(e.bias==='data'&&/data|contam|objective/.test(id))score+=12;if((e.bias==='systems'||e.bias==='infra')&&/pipeline|collective|hardware|prefill/.test(id))score+=10;if(e.bias==='post'&&/objective|sampling/.test(id))score+=12;if(e.bias==='evals'&&/contam|harness|eval/.test(id))score+=12;return{id,label,score}})}
function normalizeBeliefs(list){const min=Math.min(...list.map(x=>x.score),0),a=list.map(x=>({...x,score:x.score-min+1})),total=a.reduce((s,x)=>s+x.score,0)||1;return a.map(x=>({...x,prob:Math.round(x.score/total*100)})).sort((x,y)=>y.prob-x.prob)}
function ensureEmployeeBelief(e,inc){ensureNpcBeliefs();if(!e.beliefs[inc.id])e.beliefs[inc.id]={hypotheses:normalizeBeliefs(initialBeliefs(e,inc)),rationale:'Initial opinion from role experience; no incident evidence shared yet.'};e.evidenceSeen[inc.id] ||= [];return e.beliefs[inc.id]}
function beliefEvidence(){const w=typeof ws==='function'?ws():state.workstation;return (w?.evidence||[]).map((x,i)=>({...x,evidenceId:`${x.tool||'obs'}-${i}`}))}
function evidenceImpact(e,inc,ev,hid){const c=WORKSTATION_CASES?.[inc.id];if(!c)return 0;const d=incidentDomain(inc),skill=e.skills[d]||3;let n=0;if(ev.signal&&hid===c.correctHypothesis)n+=18+skill;if(c.decisive?.includes(ev.tool)&&hid===c.correctHypothesis)n+=12+Math.floor(skill/2);const t=String(ev.text||'').toLowerCase();const neg={hardware_fault:['healthy','nominal','no ecc'],collective_fault:['normal','no rank timeout','within expected'],dataloader:['wait <1%','queues remain populated'],decode_kernel:['decode kernels remain','itl p99'],harness:['unchanged','same evaluation harness']};if((neg[hid]||[]).some(p=>t.includes(p)))n-=14;if(e.bias==='data'&&ev.tool==='data')n+=hid===c.correctHypothesis?7:2;if((e.bias==='systems'||e.bias==='infra')&&['profiler','gpu','nccl','config'].includes(ev.tool))n+=hid===c.correctHypothesis?6:1;if(e.bias==='evals'&&['metrics','data','config'].includes(ev.tool))n+=hid===c.correctHypothesis?6:1;return n}
function shareEvidenceWithNpc(employeeId,evidenceId){ensureNpcBeliefs();const e=npcById(employeeId),inc=beliefIncident(),ev=beliefEvidence().find(x=>x.evidenceId===evidenceId);if(!e||!inc||!ev)return;const seen=e.evidenceSeen[inc.id]||=[];if(seen.includes(evidenceId))return;seen.push(evidenceId);const b=ensureEmployeeBelief(e,inc);b.hypotheses=normalizeBeliefs(b.hypotheses.map(h=>({...h,score:(h.score||h.prob)+evidenceImpact(e,inc,ev,h.id)})));const top=b.hypotheses[0];b.rationale=`After reviewing ${ev.title||ev.tool}, ${top.label} is my leading hypothesis at ${top.prob}%.`;npcRemember(e,`You shared ${ev.title||ev.tool} evidence during ${inc.title}.`,inc.id);e.trust=Math.min(100,e.trust+1);save();render()}
function npcBeliefSummary(e,inc){const b=ensureEmployeeBelief(e,inc);return{belief:b,top:b.hypotheses[0],seen:e.evidenceSeen[inc.id]?.length||0}}
function renderEvidenceShare(id){const e=npcById(id),inc=beliefIncident();if(!e||!inc)return'';ensureEmployeeBelief(e,inc);const rows=beliefEvidence();return `<div class="belief-share"><div class="eyebrow">EVIDENCE ACCESS</div><p>${esc(e.name)} has seen ${e.evidenceSeen[inc.id].length} of ${rows.length} collected observations.</p>${rows.length?rows.map(ev=>`<button class="${e.evidenceSeen[inc.id].includes(ev.evidenceId)?'seen':''}" onclick="shareEvidenceWithNpc('${e.id}','${ev.evidenceId}')" ${e.evidenceSeen[inc.id].includes(ev.evidenceId)?'disabled':''}><span>${esc(ev.title||ev.tool)}</span><small>${esc(ev.text)}</small><b>${e.evidenceSeen[inc.id].includes(ev.evidenceId)?'SHARED':'SHARE'}</b></button>`).join(''):'<div class="belief-empty">Collect workstation evidence first.</div>'}</div>`}
function renderBeliefCard(e,inc){const s=npcBeliefSummary(e,inc);return `<article class="belief-card"><header><span class="npc-avatar mini ${e.color}">${esc(e.avatar)}</span><div><b>${esc(e.name)}</b><small>${esc(e.specialty)}</small></div><em>${s.seen} evidence</em></header><div class="belief-lead"><span>LEADING HYPOTHESIS</span><b>${esc(s.top?.label||'Unknown')}</b><strong>${s.top?.prob||0}%</strong></div><div class="belief-bars">${s.belief.hypotheses.map(h=>`<div><span>${esc(h.label)}</span><i><em style="width:${h.prob}%"></em></i><b>${h.prob}%</b></div>`).join('')}</div><p>${esc(s.belief.rationale)}</p></article>`}
function npcRoundtableOpen(){ensureNpcBeliefs();state.npcBeliefs.roundtableOpen=true;save();render()}
function npcRoundtableClose(){state.npcBeliefs.roundtableOpen=false;save();render()}
function renderNpcRoundtable(){if(!state.npcBeliefs?.roundtableOpen||!state.selectedIncident)return'';const inc=beliefIncident();if(!inc)return'';const leaders=new Set(state.npcEmployees.map(e=>npcBeliefSummary(e,inc).top?.id));const disagreement=leaders.size>1;return `<div class="roundtable-back"><div class="roundtable"><header><div><div class="eyebrow">INCIDENT ROUNDTABLE</div><h2>${esc(inc.title)}</h2><p>${disagreement?'Your team disagrees. Compare what each person has actually seen before making the call.':'The team currently converges, but confidence and evidence access still differ.'}</p></div><button onclick="npcRoundtableClose()">Close</button></header><div class="roundtable-grid">${state.npcEmployees.map(e=>renderBeliefCard(e,inc)).join('')}</div></div></div>`}
function renderBeliefAdviceAddon(){const a=state.npcTeam?.advice;if(!a||!state.selectedIncident)return'';const e=npcById(a.employeeId),inc=beliefIncident();if(!e||!inc)return'';const s=npcBeliefSummary(e,inc);return `<div class="belief-advice-addon"><div class="belief-lead"><span>CURRENT BELIEF</span><b>${esc(s.top?.label||'Unknown')}</b><strong>${s.top?.prob||0}%</strong></div>${renderEvidenceShare(e.id)}<button class="roundtable-btn" onclick="npcRoundtableOpen()">Bring the team into a roundtable</button></div>`}
const beliefBaseRenderNpcAdvice=renderNpcAdvice;renderNpcAdvice=function(){return beliefBaseRenderNpcAdvice()+renderBeliefAdviceAddon()+renderNpcRoundtable()};
ensureNpcBeliefs();