// Phase 4B.3A — Persistent Incident History + Postmortems
const ORG_HISTORY_VERSION=1;
function ensureOrgHistory(){
  state.organization ||= {version:ORG_HISTORY_VERSION,incidents:[],postmortems:[],actionItems:[],nextIncidentId:1,nextPostmortemId:1,nextActionId:1};
  state.organization.incidents ||= []; state.organization.postmortems ||= []; state.organization.actionItems ||= [];
}
function activeIncidentRecord(){ensureOrgHistory();return state.organization.incidents.find(x=>x.status==='open'&&x.incidentType===state.selectedIncident)||null}
function orgModelId(){if(state.activeRun?.modelId)return state.activeRun.modelId;return state.models?.at(-1)?.id||null}
function orgEvent(type,data={}){const r=activeIncidentRecord();if(!r)return;r.timeline.push({minute:state.ws?.minutes||0,day:state.day,type,...data})}
function ensureIncidentRecord(type){
  ensureOrgHistory();let r=state.organization.incidents.find(x=>x.status==='open'&&x.incidentType===type);if(r)return r;
  const inc=INCIDENTS.find(x=>x.id===type);r={id:`INC-${String(state.organization.nextIncidentId++).padStart(4,'0')}`,incidentType:type,title:inc?.title||type,role:inc?.role||'',modelId:orgModelId(),openedDay:state.day,resolvedDay:null,status:'open',severity:2,timeline:[],participants:{},beliefHistory:{},evidence:[],diagnosis:null,rootCause:null,grade:null,impact:null,postmortemId:null};
  r.timeline.push({minute:0,day:state.day,type:'incident.opened'});state.organization.incidents.push(r);return r;
}
function participant(id,role='Consulted'){const r=activeIncidentRecord();if(!r)return null;r.participants[id] ||= {employeeId:id,role,consultations:0,evidenceSeen:[],beliefUpdates:0};return r.participants[id]}
function snapshotBeliefs(employeeId,label='snapshot'){
  const r=activeIncidentRecord();if(!r)return;const key=`${employeeId}:${r.incidentType}`;const b=state.npcBeliefs?.beliefs?.[key];if(!b)return;
  r.beliefHistory[employeeId] ||= [];r.beliefHistory[employeeId].push({minute:state.ws?.minutes||0,label,probabilities:{...b.probabilities},seen:[...(b.seen||[])]});
}
const orgOpenIncident=openIncident;
openIncident=function(id){const out=orgOpenIncident(id);ensureIncidentRecord(id);save();return out};
if(typeof wsTool==='function'){const orgWsTool=wsTool;wsTool=function(name){ensureIncidentRecord(state.selectedIncident);orgEvent('workstation.tool_opened',{tool:name});return orgWsTool(name)}}
if(typeof wsCommand==='function'){const orgWsCommand=wsCommand;wsCommand=function(){const v=document.getElementById('wsCommand')?.value?.trim();if(v)orgEvent('workstation.command',{command:v});return orgWsCommand()}}
if(typeof askNpcDuringIncident==='function'){const orgAsk=askNpcDuringIncident;askNpcDuringIncident=function(id){ensureIncidentRecord(state.selectedIncident);const p=participant(id);if(p)p.consultations++;orgEvent('npc.consulted',{employeeId:id});const out=orgAsk(id);snapshotBeliefs(id,'consulted');return out}}
if(typeof shareEvidenceWithNpc==='function'){const orgShare=shareEvidenceWithNpc;shareEvidenceWithNpc=function(employeeId,evidenceId){ensureIncidentRecord(state.selectedIncident);const r=activeIncidentRecord(),p=participant(employeeId,'Contributor');if(p&&!p.evidenceSeen.includes(evidenceId))p.evidenceSeen.push(evidenceId);if(r&&!r.evidence.some(x=>x.employeeId===employeeId&&x.evidenceId===evidenceId))r.evidence.push({minute:state.ws?.minutes||0,employeeId,evidenceId});snapshotBeliefs(employeeId,'before_evidence');const out=orgShare(employeeId,evidenceId);snapshotBeliefs(employeeId,'after_evidence');if(p)p.beliefUpdates++;orgEvent('incident.evidence_shared',{employeeId,evidenceId});save();return out}}
function gradeIncident(r,efficiency){
  const participants=Object.keys(r.participants).length,evidence=r.evidence.length,tools=state.ws?.visited?.length||0;
  const correctness=100,eff=Math.max(0,Math.min(100,efficiency||50)),evidenceScore=Math.min(100,35+tools*9+evidence*7),team=Math.min(100,45+participants*9);
  const total=Math.round(correctness*.35+eff*.3+evidenceScore*.2+team*.15);return {letter:total>=92?'S':total>=82?'A':total>=70?'B':total>=58?'C':'D',total,dimensions:{technicalCorrectness:correctness,efficiency:eff,evidenceQuality:evidenceScore,teamCoordination:team}};
}
function buildPostmortem(r,choice,efficiency){
  ensureOrgHistory();const inc=INCIDENTS.find(x=>x.id===r.incidentType);const correct=choice||inc?.choices?.find(x=>x[3]);const grade=gradeIncident(r,efficiency);
  const root=correct?.[2]||'Root cause confirmed through the incident investigation.';
  const wentWell=[];if((state.ws?.visited?.length||0)>=3)wentWell.push('Multiple diagnostic surfaces were inspected before committing a production action.');if(r.evidence.length)wentWell.push('Evidence was explicitly shared with team members before or during diagnosis.');if(Object.keys(r.participants).length>1)wentWell.push('The incident used multiple engineering perspectives instead of a single hint source.');if(!wentWell.length)wentWell.push('The final production action resolved the incident.');
  const poor=[];if((state.ws?.visited?.length||0)>6)poor.push('The investigation spread across many tools; a tighter falsification plan may have reduced time-to-diagnosis.');if(!r.evidence.length)poor.push('No diagnostic artifact was explicitly shared with the team.');if(Object.keys(r.participants).length===0)poor.push('The incident was resolved without using the engineering team.');if(!poor.length)poor.push('No major process failure was identified in this simulation.');
  const pm={id:`PM-${String(state.organization.nextPostmortemId++).padStart(4,'0')}`,incidentId:r.id,modelId:r.modelId,createdDay:state.day,summary:`${r.title} was resolved with a ${grade.letter} incident grade.`,rootCause:root,contributingFactors:incidentContributors(r.incidentType),whatWentWell:wentWell,whatWentPoorly:poor,grade,team:Object.values(r.participants),timeline:[...r.timeline],actionItemIds:[]};
  const actions=correctiveActionTemplates(r.incidentType);actions.forEach(a=>{const item={id:`ACT-${String(state.organization.nextActionId++).padStart(4,'0')}`,incidentId:r.id,postmortemId:pm.id,title:a.title,ownerId:a.owner,status:'open',priority:a.priority,effect:a.effect,engineeringDays:a.days};state.organization.actionItems.push(item);pm.actionItemIds.push(item.id)});
  state.organization.postmortems.push(pm);r.postmortemId=pm.id;r.grade=grade;r.rootCause=root;r.diagnosis=correct?.[1]||'Resolved';r.impact={investigationMinutes:state.ws?.minutes||0,simulatedH100h:state.ws?.computeCost||0,engineeringHours:Math.max(1,Math.round((state.ws?.minutes||1)/60*Object.keys(r.participants).length))};return pm;
}
function incidentContributors(type){const m={nan:['A new data shard entered at the failure boundary.','Activation monitoring did not prevent the bad batch from reaching the run.'],bubble:['Pipeline degree increased faster than useful in-flight microbatches.','Scale-up review did not catch fill/drain overhead before launch.'],contam:['Training-data provenance allowed high-similarity material into the corpus.','Headline benchmark movement exceeded control improvements.'],ttft:['Long prompts shared capacity with short interactive traffic.','Prefill queue pressure was not isolated from decode latency.'],dpo:['Preference data overrepresented conversational style.','Release criteria over-weighted aggregate preference win rate.']};return m[type]||[]}
function correctiveActionTemplates(type){const m={nan:[{title:'Add shard anomaly and finite-activation validation',owner:'rafael',priority:'high',days:2,effect:'Earlier detection of pathological shards'},{title:'Automate deterministic bad-batch replay',owner:'maya',priority:'medium',days:2,effect:'Faster root-cause isolation'}],bubble:[{title:'Add pipeline idle alert and scale-review gate',owner:'maya',priority:'high',days:2,effect:'Earlier pipeline bubble detection'},{title:'Add PP × microbatch throughput sweep to launch checklist',owner:'marcus',priority:'medium',days:2,effect:'Lower recurrence risk'}],contam:[{title:'Add provenance-aware benchmark decontamination gate',owner:'zoe',priority:'high',days:3,effect:'Lower contamination risk'},{title:'Audit refreshed corpus for near-duplicate eval material',owner:'rafael',priority:'high',days:3,effect:'Cleaner measurement'}],ttft:[{title:'Add prefill-queue SLO and long-prompt dashboard',owner:'noah',priority:'high',days:2,effect:'Earlier TTFT detection'},{title:'Separate long-prompt serving capacity',owner:'marcus',priority:'medium',days:3,effect:'Lower burst coupling'}],dpo:[{title:'Add tool exactness and benign-refusal release gates',owner:'priya',priority:'high',days:2,effect:'Prevent aggregate-score masking'},{title:'Rebalance structured tool trajectories',owner:'priya',priority:'medium',days:3,effect:'Lower post-training regression risk'}]};return m[type]||[]}
const orgSolveIncident=solveIncident;
solveIncident=function(id){
  ensureIncidentRecord(state.selectedIncident);const r=activeIncidentRecord(),inc=INCIDENTS.find(x=>x.id===state.selectedIncident),choice=inc?.choices?.find(x=>x[0]===id),ok=!!choice?.[3],eff=typeof diagnosticEfficiency==='function'?diagnosticEfficiency():50;
  orgEvent('incident.action_taken',{choiceId:id,choice:choice?.[1]});const out=orgSolveIncident(id);
  if(ok&&r){r.status='resolved';r.resolvedDay=state.day;r.timeline.push({minute:state.ws?.minutes||0,day:state.day,type:'incident.resolved',choiceId:id});buildPostmortem(r,choice,eff);Object.keys(r.participants).forEach(pid=>{const e=npcById?.(pid);if(e)npcRemember(e,`Postmortem ${r.postmortemId}: ${r.title} resolved with grade ${r.grade.letter}.`,r.incidentType)});save()}
  return out;
};
function completeCorrectiveAction(id){ensureOrgHistory();const a=state.organization.actionItems.find(x=>x.id===id);if(!a||a.status==='complete')return;a.status='complete';a.completedDay=state.day;const e=typeof npcById==='function'?npcById(a.ownerId):null;if(e){e.workload=Math.max(0,e.workload-3);npcRemember(e,`Completed corrective action: ${a.title}.`,'postmortem')}log(`✅ Corrective action completed: ${a.title}.`);save();render()}
function openPostmortems(){ensureOrgHistory();state.view='postmortems';save();render()}
function closePostmortems(){state.view='company';save();render()}
function renderPostmortems(){ensureOrgHistory();const pms=state.organization.postmortems.slice().reverse();return `<div class="pm-shell"><header class="pm-head"><div><div class="eyebrow">PHASE 4B.3A · ORGANIZATIONAL MEMORY</div><h1>Incident Postmortems</h1><p>Every resolved incident now leaves an auditable technical and team history.</p></div><button onclick="closePostmortems()">Return to company</button></header><main class="pm-main">${pms.length?pms.map(pm=>renderPostmortemCard(pm)).join(''):`<section class="pm-card empty"><h2>No postmortems yet</h2><p>Resolve a live incident and its investigation will appear here.</p></section>`}</main></div>`}
function renderPostmortemCard(pm){const r=state.organization.incidents.find(x=>x.id===pm.incidentId);const actions=state.organization.actionItems.filter(x=>x.postmortemId===pm.id);return `<article class="pm-card"><header><div><span>${pm.id} · ${r?.id||''}</span><h2>${esc(r?.title||'Incident')}</h2><small>Day ${r?.openedDay} → ${r?.resolvedDay} · Model ${esc(r?.modelId||'unlinked')}</small></div><div class="pm-grade ${pm.grade.letter.toLowerCase()}"><b>${pm.grade.letter}</b><span>${pm.grade.total}</span></div></header><div class="pm-grid"><section><h3>Root cause</h3><p>${esc(pm.rootCause)}</p><h3>Contributing factors</h3>${pm.contributingFactors.map(x=>`<p>• ${esc(x)}</p>`).join('')}</section><section><h3>What went well</h3>${pm.whatWentWell.map(x=>`<p class="good">✓ ${esc(x)}</p>`).join('')}<h3>What went poorly</h3>${pm.whatWentPoorly.map(x=>`<p class="bad">• ${esc(x)}</p>`).join('')}</section><section><h3>Team</h3>${pm.team.length?pm.team.map(x=>`<div class="pm-person"><b>${esc(npcById?.(x.employeeId)?.name||x.employeeId)}</b><span>${esc(x.role)} · ${x.consultations} consults · ${x.evidenceSeen.length} artifacts</span></div>`).join(''):'<p>No NPC participation recorded.</p>'}<h3>Impact</h3><p>${r?.impact?.investigationMinutes||0}m investigation · ${(r?.impact?.simulatedH100h||0).toFixed(1)} simulated H100h</p></section></div><section class="pm-actions"><h3>Corrective actions</h3>${actions.map(a=>`<div class="pm-action ${a.status}"><div><b>${esc(a.title)}</b><span>${esc(npcById?.(a.ownerId)?.name||a.ownerId)} · ${a.priority} · ${a.engineeringDays}d</span><small>${esc(a.effect)}</small></div>${a.status==='open'?`<button onclick="completeCorrectiveAction('${a.id}')">Complete</button>`:'<em>Completed</em>'}</div>`).join('')}</section></article>`}
// Extend Model Lab History with incident records.
if(typeof modelLabHistory==='function'){const orgModelHistory=modelLabHistory;modelLabHistory=function(m){const base=orgModelHistory(m);ensureOrgHistory();const rows=state.organization.incidents.filter(x=>x.modelId===m.id&&x.status==='resolved').map(r=>`<div class="history-row"><span>Day ${r.resolvedDay}</span><b>${esc(r.title)} · ${r.grade?.letter||'—'} grade</b><em>${esc(r.id)}</em></div>`).join('');return base.replace('</div>',`<section class="lab-panel wide"><div class="eyebrow">INCIDENT HISTORY</div><h3>Production and training failures</h3>${rows||'<div class="lab-empty">No linked incidents yet.</div>'}</section></div>`)}}
const orgRender=render;
render=function(){ensureOrgHistory();if(state.view==='postmortems'){document.getElementById('app').innerHTML=renderPostmortems();return}orgRender();if(!state.started)return;const shell=document.querySelector('.game-shell');if(!shell)return;const b=document.createElement('button');b.className='pm-launch';b.onclick=openPostmortems;b.innerHTML=`<span>POSTMORTEMS</span><b>${state.organization.postmortems.length} incident record${state.organization.postmortems.length===1?'':'s'}</b><small>Root causes · team reasoning · corrective actions →</small>`;shell.insertBefore(b,shell.children[2]||null)};
render();
