const STORY_VERSION=1;
const STORY_INTRO={title:'The First Night',kicker:'FOUNDER STORY',objective:'Meet the team, choose your role, then open one lab and make your first technical decision.',frames:[['Narrator','11:47 PM. The lease is signed. The racks are loud. The company account has less runway than anyone in the room wants to admit.'],['Maya Chen','The cluster is alive. Barely. If we are serious about frontier work, we need to learn faster than we burn money.'],['Elena Kovacs','Then we build something worth learning from. Small model first. Clean evidence. No vanity scaling.'],['You','Tomorrow this becomes a company. Tonight, we make the first call.']]};
function ensureStory(){state.story ||= {version:STORY_VERSION,seen:[],active:null,index:0,objective:null};state.story.seen ||= []}
function showStoryIntro(){ensureStory();state.story.active='intro';state.story.index=0;state.story.objective=STORY_INTRO.objective;save();render()}
function storyNext(){ensureStory();if(state.story.index<STORY_INTRO.frames.length-1){state.story.index++;save();render()}else storyClose()}
function storyClose(){ensureStory();if(!state.story.seen.includes('intro'))state.story.seen.push('intro');state.story.active=null;state.story.index=0;save();render()}
function renderStoryIntro(){ensureStory();const f=STORY_INTRO.frames[state.story.index],pct=Math.round((state.story.index+1)/STORY_INTRO.frames.length*100);return `<div class="story-scene"><div class="story-stage"><div class="story-character"><b>${esc(f[0]==='You'?'YOU':f[0].split(' ').map(x=>x[0]).join('').slice(0,2))}</b></div><div class="story-objective"><span>NEXT OBJECTIVE</span><b>${esc(STORY_INTRO.objective)}</b></div><div class="story-box"><div class="story-kicker">${esc(STORY_INTRO.kicker)}</div><div class="story-speaker">${esc(f[0])}</div><p>${esc(f[1])}</p><div class="story-progress"><i style="width:${pct}%"></i></div><div class="story-actions"><button class="story-skip" onclick="storyClose()">Skip scene</button><button class="story-next" onclick="storyNext()">${state.story.index===STORY_INTRO.frames.length-1?'Enter the lab →':'Continue →'}</button></div></div></div></div>`}
function storyObjective(){ensureStory();if(!state.story.objective||state.story.active)return'';return `<aside class="story-next-move"><div><span>YOUR NEXT MOVE</span><b>${esc(state.story.objective)}</b></div><button onclick="state.story.objective=null;save();render()">Got it</button></aside>`}
const storyFoundBase=foundLab;
foundLab=function(){storyFoundBase();if(state.started){ensureStory();if(!state.story.seen.includes('intro'))showStoryIntro()}};
const storyRenderBase=render;
render=function(){ensureStory();if(state.story.active==='intro'){document.getElementById('app').innerHTML=renderStoryIntro();return}storyRenderBase();if(!state.started)return;const shell=document.querySelector('.game-shell');if(shell&&!shell.querySelector('.story-next-move'))shell.insertAdjacentHTML('afterbegin',storyObjective())};
render();