const CACHE='frontier-lab-v14';
const CORE=[
  './','./index.html','./manifest.webmanifest','./frontier-lab-icon.svg',
  './theme-tokens.css','./styles.css','./v3-extra.css','./workstation.css','./momentum.css','./model-lab.css','./npc-team.css','./npc-beliefs.css','./postmortems.css','./knowledge.css','./career.css','./hiring.css','./engineering-artifacts.css','./incident-artifacts.css','./code-lab.css','./data-evals.css','./tech-debt.css','./debt-consequences.css','./architecture-migrations.css','./family-forks.css','./maintenance-economics.css','./operations-ownership.css','./slo-reliability.css','./release-governance.css','./roadmap-enterprise.css','./quarterly-board.css','./financing-strategy.css','./macro-restructuring.css','./governance-board.css','./executive-politics.css','./employee-talent-memory.css','./org-management.css','./workforce-planning.css','./project-portfolio.css','./critical-path.css','./program-management.css','./program-learning.css','./portfolio-strategy.css','./investment-committee.css','./competitive-intelligence.css','./ecosystem-strategy.css','./policy-regulatory.css','./public-communications.css','./mobile-ux.css','./responsive-gameplay-shell.css','./app-experience.css','./early-game-progression.css','./game-feel.css','./balance-pacing.css','./technical-realism.css','./replayability.css','./browser-default-firewall.css','./shared-surface-system.css','./progressive-disclosure.css',
  './frontier-lab.js','./runtime-compat.js','./economy.js','./workstation.js','./momentum.js','./engagement.js','./model-lab.js','./npc-team.js','./npc-beliefs.js','./postmortems.js','./knowledge.js','./career.js','./hiring.js','./engineering-artifacts.js','./incident-artifacts.js','./code-lab.js','./data-evals.js','./tech-debt.js','./debt-consequences.js','./architecture-migrations.js','./family-forks.js','./maintenance-economics.js','./maintenance-deadline-guard.js','./operations-ownership.js','./slo-reliability.js','./release-governance.js','./roadmap-enterprise.js','./quarterly-board.js','./financing-strategy.js','./macro-restructuring.js','./governance-board.js','./executive-politics.js','./employee-talent-memory.js','./org-management.js','./workforce-planning.js','./project-portfolio.js','./critical-path.js','./program-management.js','./program-learning.js','./portfolio-strategy.js','./investment-committee.js','./competitive-intelligence.js','./ecosystem-strategy.js','./policy-regulatory.js','./public-communications.js','./ui-components.js','./pwa-runtime.js','./early-game-progression.js','./responsive-gameplay-shell.js','./progressive-disclosure.js','./story-integration.js','./game-feel.js','./balance-pacing.js','./technical-realism.js','./replayability.js','./replayability-canonical.js','./replayability-realism.js','./shared-surface-system.js'
];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;
  if(req.mode==='navigate'){event.respondWith(fetch(req).then(res=>{const copy=res.clone();caches.open(CACHE).then(c=>c.put('./index.html',copy));return res}).catch(()=>caches.match('./index.html')));return}
  event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(res=>{if(res&&res.ok){const copy=res.clone();caches.open(CACHE).then(c=>c.put(req,copy))}return res})));
});