import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';
const base=process.env.TEST_URL||'http://127.0.0.1:4173/';const out=path.resolve('artifacts/frontieros-session');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true});const errors=[];
// Phone: history, back/forward, notification deep link, persistence.
const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await phone.tracing.start({screenshots:true,snapshots:true,sources:true});const p=await phone.newPage();p.on('pageerror',e=>errors.push(String(e?.stack||e)));
await p.goto(`${base}${base.includes('?')?'&':'?'}frontieros=1`,{waitUntil:'networkidle'});await p.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await p.reload({waitUntil:'networkidle'});await p.locator('.frontieros-phone-shell').waitFor({state:'visible'});
await p.evaluate(()=>frontierOsNavigate('training'));await p.locator('.frontieros-mobile-appbar').waitFor({state:'visible'});await p.evaluate(()=>frontierOsNavigate('model-lab'));
let snap=await p.evaluate(()=>frontierOsSessionSnapshot());assert(snap.history.length>=2,'navigation history did not record app transitions');assert.equal(snap.current.appId,'model-lab');assert.equal(snap.canBack,true);assert.equal(snap.recents[0].appId,'model-lab');
await p.evaluate(()=>frontierOsBack());assert.equal((await p.evaluate(()=>frontierOsSessionSnapshot())).current.appId,'training','Back did not restore Run Monitor history entry');await p.evaluate(()=>frontierOsForward());assert.equal((await p.evaluate(()=>frontierOsSessionSnapshot())).current.appId,'model-lab','Forward did not restore Model Lab history entry');
const note=await p.evaluate(()=>frontierOsNotify({title:'Run 1842 halted',body:'NaN detected. Open Run Monitor.',deepLink:'frontieros://training/run-1842',severity:'warn',source:'qa'}));assert(note.id,'notification id missing');assert.equal((await p.evaluate(()=>frontierOsSessionSnapshot())).unread,1);
await p.evaluate(()=>frontierOsOpenNotificationCenter());await p.locator('.frontieros-notification-center').waitFor({state:'visible'});assert(await p.getByText('Run 1842 halted').isVisible(),'notification center did not render alert');await p.screenshot({path:path.join(out,'phone-notification-center.png'),fullPage:true});
await p.locator(`[data-note-open="${note.id}"]`).click();await p.waitForTimeout(100);snap=await p.evaluate(()=>frontierOsSessionSnapshot());assert.equal(snap.current.appId,'training','notification deep link did not open Run Monitor');assert.equal(snap.current.detail,'run-1842','deep-link detail was not preserved in navigation history');assert.equal(snap.unread,0,'opening notification did not mark it read');
const beforeReload=await p.evaluate(()=>frontierOsSessionSnapshot());await p.reload({waitUntil:'networkidle'});await p.locator('.frontieros-phone-shell').waitFor({state:'visible'});const restored=await p.evaluate(()=>frontierOsSessionSnapshot());assert.equal(restored.current.appId,beforeReload.current.appId,'session current app metadata did not survive reload');assert.equal(restored.history.length,beforeReload.history.length,'history did not survive reload');assert(restored.recents.some(x=>x.appId==='training'),'recent apps did not survive reload');assert.equal(restored.notifications.length,beforeReload.notifications.length,'notification state did not survive reload');
await p.evaluate(()=>frontierOsOpenNotificationCenter());await p.screenshot({path:path.join(out,'phone-restored-session.png'),fullPage:true});await p.evaluate(()=>frontierOsCloseNotificationCenter());
const phoneEvents=await p.evaluate(()=>frontierEventJournal({type:'os.*',limit:250}));assert(phoneEvents.some(e=>e.type==='os.session.restored'),'session restore event missing');assert(phoneEvents.some(e=>e.type==='os.navigation.changed'),'navigation event missing');assert(phoneEvents.some(e=>e.type==='os.notification.opened'),'notification-open event missing');await phone.tracing.stop({path:path.join(out,'phone-trace.zip')});await phone.close();
// Desktop: shared recents + notification center + shell-aware navigation.
const desktop=await browser.newContext({viewport:{width:1440,height:1000}});const d=await desktop.newPage();d.on('pageerror',e=>errors.push(String(e?.stack||e)));await d.goto(`${base}${base.includes('?')?'&':'?'}frontieros=desktop`,{waitUntil:'networkidle'});await d.evaluate(()=>{localStorage.clear();sessionStorage.clear();localStorage.setItem('frontieros.desktop','1')});await d.reload({waitUntil:'networkidle'});await d.locator('.frontieros-desktop').waitFor({state:'visible'});
await d.evaluate(()=>frontierOsNavigate('training'));await d.evaluate(()=>frontierOsNavigate('model-lab'));const ds=await d.evaluate(()=>frontierOsSessionSnapshot());assert.equal(ds.current.appId,'model-lab');assert(ds.recents.some(x=>x.appId==='training')&&ds.recents.some(x=>x.appId==='model-lab'),'desktop recents missing launched apps');
await d.evaluate(()=>frontierOsNotify({title:'Eval finished',body:'Benchmark complete.',appId:'evals'}));await d.evaluate(()=>frontierOsOpenNotificationCenter());await d.locator('.frontieros-notification-center').waitFor({state:'visible'});await d.screenshot({path:path.join(out,'desktop-notification-center.png'),fullPage:true});assert(await d.locator('.frontieros-tray [data-os-notifications]').count()===1,'desktop notification control missing');
await desktop.close();await browser.close();assert.equal(errors.length,0,`runtime page errors: ${errors.join(' | ')}`);
const report={version:1,item:'P5.1.4',status:'pass',generatedAt:new Date().toISOString(),phoneHistory:restored.history.length,phoneRecents:restored.recents.length,phoneNotifications:restored.notifications.length,desktopCurrent:ds.current.appId,pageErrors:errors.length,evidence:['phone-notification-center.png','phone-restored-session.png','desktop-notification-center.png','phone-trace.zip']};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'REPORT.md'),`# P5.1.4 Navigation, Notifications & Session\n\n- Status: **PASS**\n- Phone back/forward history: **PASS**\n- Notification deep link: **PASS**\n- Notification read state: **PASS**\n- Reload session persistence: **PASS**\n- Recent apps: **PASS**\n- Desktop shell-aware navigation: **PASS**\n- Runtime page errors: **0**\n- Playwright trace: **captured**\n`);console.log('P5.1.4 FrontierOS session regression passed');
