import fs from 'node:fs';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';

const policy=JSON.parse(fs.readFileSync('release-gate-policy.json','utf8'));
const outRoot=path.resolve(process.env.RELEASE_GATE_DIR||'artifacts/release-gate');
const serverUrl=process.env.RELEASE_GATE_URL||'http://127.0.0.1:4173/';
const externalServer=Boolean(process.env.RELEASE_GATE_URL);
const maxBuffer=64*1024*1024;
const phaseTimeouts={preflight:120000,build:120000,browser:180000};

fs.rmSync(outRoot,{recursive:true,force:true});
fs.mkdirSync(path.join(outRoot,'logs'),{recursive:true});

const report={
  version:2,item:'13.16',policyVersion:policy.version,generatedAt:new Date().toISOString(),serverUrl,externalServer,
  environment:{node:process.version,platform:process.platform,arch:process.arch,ci:Boolean(process.env.CI),githubSha:process.env.GITHUB_SHA||null,githubRef:process.env.GITHUB_REF||null,githubEventName:process.env.GITHUB_EVENT_NAME||null},
  timeouts:{phaseDefaultsMs:phaseTimeouts},gates:[],blockers:[],advisories:[],evidence:{},releaseDecision:'pending'
};
const blocker=(type,details={})=>report.blockers.push({type,...details});
const advisory=(type,details={})=>report.advisories.push({type,...details});
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100);
function readJsonEvidence(file,severity='blocker',type='invalid-json-evidence'){if(!fs.existsSync(file))return null;try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch(error){const details={path:file,error:String(error?.message||error)};severity==='blocker'?blocker(type,details):advisory(type,details);return null}}

function runCommandGate(gate,env={}){
  const started=Date.now();const timeoutMs=Number(gate.timeoutMs||phaseTimeouts[gate.phase]||180000);
  if(gate.evidence)fs.rmSync(path.dirname(path.resolve(gate.evidence)),{recursive:true,force:true});if(gate.id==='production-build')fs.rmSync(path.resolve('_site'),{recursive:true,force:true});
  console.log(`\n=== ${gate.severity.toUpperCase()} :: ${gate.label} (${gate.script}) :: timeout ${timeoutMs}ms ===`);
  const result=spawnSync('npm',['run','--silent',gate.script],{cwd:process.cwd(),env:{...process.env,...env},encoding:'utf8',maxBuffer,timeout:timeoutMs,killSignal:'SIGTERM'});
  const stdout=result.stdout||'',stderr=result.stderr||'';if(stdout)process.stdout.write(stdout);if(stderr)process.stderr.write(stderr);
  const timedOut=result.error?.code==='ETIMEDOUT';const exitCode=Number.isInteger(result.status)?result.status:timedOut?124:1;const status=timedOut?'timeout':exitCode===0?'pass':'fail';
  const row={id:gate.id,label:gate.label,script:gate.script,severity:gate.severity,phase:gate.phase,status,exitCode,durationMs:Date.now()-started,timeoutMs,timedOut,evidence:gate.evidence||null,error:result.error?String(result.error?.message||result.error):null,signal:result.signal||null};
  report.gates.push(row);fs.writeFileSync(path.join(outRoot,'logs',`${slug(gate.id)}.log`),`# gate=${gate.id}\n# status=${status}\n# timeoutMs=${timeoutMs}\n# durationMs=${row.durationMs}\n${stdout}${stderr}`);
  if(timedOut){const details={gate:gate.id,script:gate.script,timeoutMs,durationMs:row.durationMs,error:row.error};gate.severity==='blocker'?blocker('gate-command-timeout',details):advisory('advisory-command-timeout',details)}
  else if(exitCode!==0){const details={gate:gate.id,script:gate.script,exitCode,error:row.error};gate.severity==='blocker'?blocker('gate-command-failed',details):advisory('advisory-command-failed',details)}
  if(gate.evidence&&!fs.existsSync(gate.evidence)){const details={gate:gate.id,path:gate.evidence};gate.severity==='blocker'?blocker('required-evidence-missing',details):advisory('advisory-evidence-missing',details)}
  return row;
}
function recordBlockedGate(gate,reason){const row={id:gate.id,label:gate.label,script:gate.script,severity:gate.severity,phase:gate.phase,status:'blocked',exitCode:null,durationMs:0,evidence:gate.evidence||null,reason};report.gates.push(row);const details={gate:gate.id,reason};gate.severity==='blocker'?blocker('gate-not-executed',details):advisory('advisory-not-executed',details)}
async function waitForServer(url,server,timeoutMs=15000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){if(server&&server.exitCode!==null)return false;try{const response=await fetch(url,{cache:'no-store'});if(response.ok)return true}catch{}await new Promise(r=>setTimeout(r,250))}return false}

function evaluateSemanticEvidence(){
  const semantics=policy.semanticEvidence||{},screenshotPolicy=semantics.screenshotRegression||{},baselineFile=screenshotPolicy.baselineFile||'visual-qa/screenshot-baseline.json';const baselineExists=fs.existsSync(baselineFile),baseline=readJsonEvidence(baselineFile,'blocker','screenshot-baseline-invalid');
  report.evidence.screenshotBaseline=baseline?{status:baseline.status||null,expectedCaptureCount:baseline.expectedCaptureCount||0,captureCount:Object.keys(baseline.captures||{}).length}:null;if(!baselineExists)blocker('screenshot-baseline-missing',{path:baselineFile});else if(baseline){if(baseline.status!==screenshotPolicy.requiredBaselineStatus)blocker('screenshot-baseline-inactive',{required:screenshotPolicy.requiredBaselineStatus,actual:baseline.status||null,path:baselineFile});if(Number(baseline.expectedCaptureCount)!==Number(screenshotPolicy.expectedCaptureCount))blocker('screenshot-baseline-count-contract',{expected:screenshotPolicy.expectedCaptureCount,actual:baseline.expectedCaptureCount});if(baseline.status===screenshotPolicy.requiredBaselineStatus&&Object.keys(baseline.captures||{}).length!==Number(screenshotPolicy.expectedCaptureCount))blocker('screenshot-baseline-incomplete',{expected:screenshotPolicy.expectedCaptureCount,actual:Object.keys(baseline.captures||{}).length})}
  const screenshotPath='artifacts/screenshot-regression/report.json',screenshot=readJsonEvidence(screenshotPath,'blocker','screenshot-report-invalid');if(screenshot){const summary={item:screenshot.item||null,baselineStatus:screenshot.baselineStatus||null,expectedCaptureCount:screenshot.expectedCaptureCount||0,producedCaptures:(screenshot.captures||[]).length,mismatches:(screenshot.mismatches||[]).length,missingBaseline:(screenshot.missingBaseline||[]).length,extraBaseline:(screenshot.extraBaseline||[]).length,missingCaptures:(screenshot.missingCaptures||[]).length,pageErrors:(screenshot.pageErrors||[]).length};report.evidence.screenshotRegression=summary;if(summary.item!=='13.14')blocker('screenshot-report-contract',{expectedItem:'13.14',actualItem:summary.item});if(summary.baselineStatus!==screenshotPolicy.requiredBaselineStatus)blocker('screenshot-report-baseline-status',{required:screenshotPolicy.requiredBaselineStatus,actual:summary.baselineStatus});if(summary.expectedCaptureCount!==Number(screenshotPolicy.expectedCaptureCount)||summary.producedCaptures!==Number(screenshotPolicy.expectedCaptureCount))blocker('screenshot-capture-count',{expected:screenshotPolicy.expectedCaptureCount,reportedExpected:summary.expectedCaptureCount,produced:summary.producedCaptures});for(const field of screenshotPolicy.blockOn||[]){const count=Array.isArray(screenshot[field])?screenshot[field].length:Number(screenshot[field]||0);if(count>0)blocker('screenshot-regression-evidence',{field,count})}}
  const routePolicy=semantics.routeCrawl||{},routePath='artifacts/route-crawl/report.json',routes=readJsonEvidence(routePath,'blocker','route-report-invalid');if(routes){const summary={item:routes.item||null,expectedVisits:routes.expectedVisits||0,actualVisits:(routes.visits||[]).length,failures:(routes.failures||[]).length,warnings:(routes.warnings||[]).length,orphanRuntimePages:(routes.orphanRuntimePages||[]).length};report.evidence.routeCrawl=summary;if(summary.item!=='13.15')blocker('route-report-contract',{expectedItem:'13.15',actualItem:summary.item});if(Number(summary.expectedVisits)!==Number(routePolicy.expectedVisits)||summary.actualVisits!==Number(routePolicy.expectedVisits))blocker('route-crawl-visit-count',{expected:routePolicy.expectedVisits,reportedExpected:summary.expectedVisits,actual:summary.actualVisits});if(routePolicy.blockOnFailures&&summary.failures>0)blocker('route-crawl-failures',{count:summary.failures});if(routePolicy.warningsAreAdvisory&&summary.warnings>0)advisory('route-crawl-warnings',{count:summary.warnings})}
  const visualPath='artifacts/visual-inventory/report.json',visual=readJsonEvidence(visualPath,'advisory','visual-inventory-report-invalid');if(visual){const captures=Object.values(visual.devices||{}).flatMap(device=>device.captures||[]),brightSurfaceSuspects=captures.reduce((n,capture)=>n+(capture.brightSurfaces||[]).length,0),unresolvedScreens=(visual.unresolvedScreens||[]).length;report.evidence.visualInventory={captures:captures.length,unresolvedScreens,brightSurfaceSuspects};if(semantics.visualInventory?.unresolvedScreensAreAdvisory&&unresolvedScreens)advisory('visual-inventory-unresolved',{count:unresolvedScreens});if(semantics.visualInventory?.brightSurfaceSuspectsAreAdvisory&&brightSurfaceSuspects)advisory('visual-inventory-bright-surface-suspects',{count:brightSurfaceSuspects})}
  for(const item of policy.manualChecks||[])if(item.severity==='advisory')advisory('manual-check',{id:item.id,description:item.description});
}
function writeReport(){report.releaseDecision=report.blockers.length?'block':'pass';fs.writeFileSync(path.join(outRoot,'report.json'),JSON.stringify(report,null,2)+'\n');const lines=['# Item 13.16 release gate','',`- Decision: **${report.releaseDecision.toUpperCase()}**`,`- Blockers: **${report.blockers.length}**`,`- Advisories: **${report.advisories.length}**`,`- Policy version: **${report.policyVersion}**`,`- Commit: **${report.environment.githubSha||'local'}**`,'','## Gate execution','','| Gate | Severity | Status | Exit | Duration / Timeout |','| --- | --- | --- | ---: | --- |'];for(const gate of report.gates)lines.push(`| ${gate.label} | ${gate.severity} | ${gate.status} | ${gate.exitCode??'—'} | ${gate.durationMs} / ${gate.timeoutMs??'—'} ms |`);lines.push('','## Blockers','');if(report.blockers.length)for(const x of report.blockers)lines.push(`- **${x.type}** — \`${JSON.stringify(x)}\``);else lines.push('- None.');lines.push('','## Advisories','');if(report.advisories.length)for(const x of report.advisories)lines.push(`- **${x.type}** — \`${JSON.stringify(x)}\``);else lines.push('- None.');lines.push('','## Evidence summary','', '```json',JSON.stringify(report.evidence,null,2),'```','','## Environment','', '```json',JSON.stringify(report.environment,null,2),'```','');fs.writeFileSync(path.join(outRoot,'REPORT.md'),lines.join('\n')+'\n')}

let server=null,serverLogFd=null,serverReady=externalServer;
try{
  for(const gate of policy.gates.filter(g=>g.phase==='preflight'))runCommandGate(gate);
  const buildGates=policy.gates.filter(g=>g.phase==='build');let buildPassed=true;for(const gate of buildGates){const row=runCommandGate(gate);if(gate.severity==='blocker'&&row.status!=='pass')buildPassed=false}
  if(buildPassed){if(externalServer)serverReady=await waitForServer(serverUrl,null,10000);else{serverLogFd=fs.openSync(path.join(outRoot,'server.log'),'a');server=spawn('python3',['-m','http.server','4173','--directory','_site'],{cwd:process.cwd(),stdio:['ignore',serverLogFd,serverLogFd]});serverReady=await waitForServer(serverUrl,server,15000)}}if(!serverReady)blocker('release-server-unavailable',{url:serverUrl,buildPassed});
  for(const gate of policy.gates.filter(g=>g.phase==='browser')){if(!serverReady){recordBlockedGate(gate,'production release server unavailable');continue}runCommandGate(gate,{TEST_URL:serverUrl})}
  evaluateSemanticEvidence();
}catch(error){blocker('release-gate-runner-error',{error:String(error?.stack||error)})}finally{if(server&&server.exitCode===null)server.kill('SIGTERM');if(serverLogFd!==null)try{fs.closeSync(serverLogFd)}catch{}writeReport()}
console.log(JSON.stringify({releaseGate:report.releaseDecision,blockers:report.blockers.length,advisories:report.advisories.length,report:path.join(outRoot,'REPORT.md')},null,2));if(report.releaseDecision!=='pass')process.exit(1);
